### ISSUE TITLE
Picture overflow

### ISSUE THREAD

**Issue by hmitsch** [mozilla-iam/dino-park-issues#1]
<img width="255" alt="image" src="https://user-images.githubusercontent.com/869692/48741170-8d802f00-ec5a-11e8-92de-af8cd8319644.png">

Name was anonymized via DevTools Inspector.

**Comment by hidde** [comment]
Issue is fixed in this PR: https://github.com/mozilla-iam/dino-park-front-end/pull/137

**Comment by hidde** [comment]
Issue has also been fixed by @fiji-flo  on the server side, which only generates square pictures now. 🎉
