### ISSUE TITLE
Org tree is missing a Legend explaining what "[S]" means

### ISSUE THREAD

**Issue by floatingatoll** [mozilla-iam/dino-park-issues#103]
In the bottom right corner of every face icon in the org tree (as far as I can tell), every person has an [S] icon overlaid on top of their image. Nowhere on this page is there a Legend explaining this icon, and it doesn't react to a mouseover with a helpful indication of what it means. What does it mean?

**Comment by martinthomson** [comment]
It means "Staff" apparently.

Given that almost all entries have this marking, I would suggest that it could be removed, leaving a marker only for exceptional cases.

**Comment by HerminaC** [comment]
Hello!

Yes, 'S' comes from the 'Staff' label. It actually expands to 'Staff' once you open someone's profile. Labeling like this will become more relevant and useful once we show contributors profiles (that will be labeled as such) into the app and open it up to our community (by the end of the year). Also, from a legal standpoint Mozilla is required to display clearly what type of contributor someone is - paid/non paid, employee/contractor (that info currently shows in the profile details as well).

Hope this helps!
Hermina
