### ISSUE TITLE
Changing cards in the org tree results in the wrong face being shown momentarily

### ISSUE THREAD

**Issue by floatingatoll** [mozilla-iam/dino-park-issues#105]
Steps to reproduce:

1. Clear your cache
2. Go to the p.m.o org tree
3. Select one card and observe that the userpic takes a moment to load.
4. Select another card and observe that the _previous_ userpic is displayed until the _new_ userpic finishes loading.

Whatever method is being used to lazy-load the userpic image is inappropriate in this unique circumstance, as we should never — even for a single second — display one person's face on another person's card. Please blank out the userpic when switching the card view to a new person using any* means necessary to ensure that this does not occur.

(Any, other than loading a blank image using the existing method before loading the new userpic using the existing method, since that itself lead to the same effect.)

**Comment by fiji-flo** [comment]
That should be solved now. Thanks for raising this and making such good case for fixing it.

**Comment by floatingatoll** [comment]
Sure thing - thanks for giving it consideration! Always happy to be wrong when that’s best too.
