### ISSUE TITLE
The name shown for a certain department does not match the name shown on that user's profile.

### ISSUE THREAD

**Issue by floatingatoll** [mozilla-iam/dino-park-issues#107]
The department "Internet Health Report (firstname lastname)" lists a different value of `firstname` than the profile of the person whose name matches `lastname` and heads the department.

Please work with this user to ensure that their Workday Preferred Name and the instance of their name included in the IHR department title are aligned to the same value.

**Comment by fiji-flo** [comment]
I talked with them and that was inconsistency between LDAP and Workday (technically it's a race which name wins for the initial name). After this is populated at account creation it's only changeable in people.mozilla.org as the names are not synced forth and back,

That issues was resolved. 
We keep working on streamlining the "account" (LDAP/Workday) creation process.
