### ISSUE TITLE
Add PTO indicator

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla-iam/dino-park-issues#108]
As an employee, I'd like to be able to tell if another employee outside my immediate team is on PTO.

Right now, there's no good way to determine if someone not in your immediate team is out of office. Some people/teams use a Slack indicator, or a calendar (often PTO calendars are team-private). Would be nice to have a consistent and easy way to check if someone is available on a given day.

**Comment by gdestuynder** [comment]
this would be a great feature. I wonder if the hris connector would be able to get this from a modified report (we don't get this data in the current report)

I also wonder if there are privacy implications to this, but we should definitely check with the privacy team if implemented. Alternatively, just let people self-set some away state, or read in from Slack.

**Comment by mozillamarcia** [comment]
Any update on this feature? During the holiday break it would have been great to have this feature, especially since everyone doesn't use Bugzilla/Gmail/Slack notification and today we are trying to resolve a top crash beta bug.
