### ISSUE TITLE
Desk numbers are not linked to the office desk location maps on Mana

### ISSUE THREAD

**Issue by floatingatoll** [mozilla-iam/dino-park-issues#110]
When viewing the profiles of office users, I see that some have a desk number assigned (BER1234, SFO2345). Please make these desk numbers link to a map of the office on Mana.

**Comment by viorelaioia-zz** [comment]
This is fixed in current production version. @floatingatoll , feel free to try it out.

**Comment by floatingatoll** [comment]
Thank you!
