### ISSUE TITLE
The list/grid icons in my Colleagues profile section do nothing

### ISSUE THREAD

**Issue by floatingatoll** [mozilla-iam/dino-park-issues#116]
When viewing my list of Colleagues, the list/grid icons have no effect on the view's layout.

**Comment by rleitan** [comment]
Should be greyed out and/or not clickable in this case?
@mbransn

**Comment by fiji-flo** [comment]
We hide the toggle now in case of 0/1 directs (where it did not do anything). Thanks for spotting this.

**Comment by floatingatoll** [comment]
Ah! That makes sense. Glad I could help.
