### ISSUE TITLE
Slack profile should use connected accounts, not freetext entry

### ISSUE THREAD

**Issue by floatingatoll** [mozilla-iam/dino-park-issues#118]
To fix #117 (and resolve #115), we will need to know a user's Slack workspace and unique ID in order to construct a link to their profile. Allowing users to freetext-enter their Slack Name leads to confusion (when two users share the same Name, which is true in our Slack).

Please replace the freetext entry of Slack names with an account-verification method that draws an appropriate and unique link to their Slack account, so that we can correct usability issue #117.

https://api.slack.com/docs/sign-in-with-slack#request_info

**Comment by gdestuynder** [comment]
since this is specific to Mozilla's Slack workspace, I suspect this could be done with a Slack driver automatically instead of prompting the user for it

Note: this would not be possible for bugzilla or github are not using SSO login and may have any user identifier

**Comment by gdestuynder** [comment]
(Backlog https://jira.mozilla.com/browse/IAM-170)
