### ISSUE TITLE
Clicking on a link in the footer or Discourse links on the front page should open a new tab

### ISSUE THREAD

**Issue by geroter** [mozilla-iam/dino-park-issues#12]
**Expected result**
When I click on a link that takes me away from the site, I expect that will open a new tab.

**Actual result**
Clicking on a footer link or the links on the front page to Discourse posts opens the referring URL in the same tab/window as DinoPark.

**Comment by hidde** [comment]
Thanks for reporting, I've fixed it this morning. 

The fix is in this PR, which should merge and deploy sometime today: https://github.com/mozilla-iam/dino-park-front-end/pull/142

**Comment by akatsoulas** [comment]
@hidde is this fixed?

**Comment by hidde** [comment]
@akatsoulas it is now, the fix is currently live.

Closing this issue, thanks @geroter.
