### ISSUE TITLE
Log out is disabled

### ISSUE THREAD

**Issue by agashlin** [mozilla-iam/dino-park-issues#120]
I'm not able to log out, the menu item is greyed out and mousing over it gives a "do not entrer" cursor.
![dinopark logout](https://user-images.githubusercontent.com/47995245/60457795-c2416500-9bf1-11e9-974e-1d8aa2428489.png)

I'm not sure if this is because of something I did, due to my container setup I ended up logged in on three containers at once (due to switching to dedicated GitHub and Bugzilla containers to verify those identities). I logged out of SSO but this is still logged in.

**Comment by viorelaioia-zz** [comment]
The logout feature was implemented and it's currently available in people.mozilla.org. @agashlin , feel free to try it out.
Closing the ticket.
