### ISSUE TITLE
Search cancellation button is misaligned

### ISSUE THREAD

**Issue by valenting** [mozilla-iam/dino-park-issues#122]
![image](https://user-images.githubusercontent.com/1454649/60461370-a320f280-9c46-11e9-91a6-dc7c1306fea3.png)

Type a few characters in the search box.
You'll notice that the `X` to cancel the search is not properly aligned, instead it's lower than it should be.

**Comment by viorelaioia-zz** [comment]
Hi @valenting ! Thanks for logging this issue!
It is mirrored in our internal jira ticket: https://jira.mozilla.com/browse/DP-1353.
We'll add a comment here when it's fixed.

**Comment by viorelaioia-zz** [comment]
This issue was fixed.
