### ISSUE TITLE
Present to bugzilla as people.m.o

### ISSUE THREAD

**Issue by martinthomson** [mozilla-iam/dino-park-issues#123]
The identity shown when authorizing with Bugzilla is "DinoPark Prod", which is a little disturbing unless you understand how this all fits together.  people.mozilla.org would be less surprising.

**Comment by HerminaC** [comment]
This makes total sense, thank you for sending. DinoPark is the internal product name, but we will change it so that is not confusing.

**Comment by fiji-flo** [comment]
I should say _people.mozilla.org_ now. Thanks!
