### ISSUE TITLE
Consider allowing accounts to have different privacy levels

### ISSUE THREAD

**Issue by Standard8** [mozilla-iam/dino-park-issues#125]
I can set different privacy levels for identities, but not for accounts.

For example, I'd like to set my irc nickname to public, but there's almost no point of that for Slack, as the Mozilla Slack isn't public.

**Comment by HerminaC** [comment]
Hey @Standard8,

This si indeed something that would make sense and we currently don't have implemented. We will do it, but it's part of a bigger change we want to make, that involves setting different privacy levels for access groups (a new feature we are currently developing). We will address the Accounts as well when writing the API for access groups, in the next couple of months (most probably end of September). 

Hope this helps,
Hermina
