### ISSUE TITLE
search results are an error loop

### ISSUE THREAD

**Issue by gcoxmoz** [mozilla-iam/dino-park-issues#128]
STR:
OSX 10.14.5, Firefox ESR 60.7.2.
https://people.mozilla.org/
In the search box "Search People by Name", I type in anyone.

Result:
New page, https://people.mozilla.org/s?query=gcox&who=staff  that says
"This page isn't available / An error occurred while trying to load the search results / Please submit all bugs or issues to the project's GitHub issue repository (link in footer)"
This goes into a refresh loop.  Like, as soon as the page renders with the error, it retries the same thing with the same results.

This never worked for me in ESR.  Does work in Chrome / 75.0.3770.100.

**Comment by fiji-flo** [comment]
Sorry for this inconvenience. This should be fixed now.

**Comment by gcoxmoz** [comment]
Confirmed, thanks
