### ISSUE TITLE
SSO authentication error

### ISSUE THREAD

**Issue by emmairwin** [mozilla-iam/dino-park-issues#13]
Hi, 

I logged in with Mozillians (as instructed)
I then went to https://people.allizom.community 
Was redirected to the SSO login.  I get this error with no specific details:
![mozilla_sso_dashboard_-_2018-11-22_16 21 28](https://user-images.githubusercontent.com/60618/48924937-ea563200-ee72-11e8-94c5-64847f631f26.png)

**Comment by hmitsch** [comment]
Hi @emmairwin,

glad things worked in the end. You are right, we need to refine login errors. We have this on our backlog. Thanks a lot!

Best regards,
   Henrik

**Comment by akatsoulas** [comment]
Thanks for @emmairwin for filing this. I am closing this issue as login is working. The UX experience will be handled in a different issue.
