### ISSUE TITLE
Searching via slack/irc accounts fails

### ISSUE THREAD

**Issue by cknowles-moz** [mozilla-iam/dino-park-issues#130]
For users that use IRC/slack that are different from their names, it would be nice if searching for the IRC/Slack handle would turn up their entry.

For example, Justin Dow - "Jabba" in IRC/Slack - if I search for Jabba - nothing turns up - though he has his IRC/Slack identities setup in dino-park.

**Comment by globau** [comment]
related: #78, #138

**Comment by viorelaioia-zz** [comment]
This has been fixed, searching after irc/slack handles returns the expected results.
