### ISSUE TITLE
Make tags and languages searchable

### ISSUE THREAD

**Issue by andreastt** [mozilla-iam/dino-park-issues#134]
You can add tags to your profile, which seems like a useful feature. I couldn’t, however, find a way to seach for tags.

**Comment by fiji-flo** [comment]
making the tags links is on it's way. For now you can do https://people.mozilla.org/s?query=tags%3ARust&who=staff

**Comment by jens1o** [comment]
I'd really like to see this as well to quickly get a sense about who I can connect to. :)

**Comment by Mte90** [comment]
Also I have to click manually for any tags to add it?
I copied and past mine from mozillians:
![immagine](https://user-images.githubusercontent.com/403283/67937978-da8cb500-fbce-11e9-8c82-4b46a4a4107e.png)

I will leave my profile broken https://people.mozilla.org/p/Mte90
