### ISSUE TITLE
https://phonebook.mozilla.org/ should redirect to https://people.mozilla.org/

### ISSUE THREAD

**Issue by globau** [mozilla-iam/dino-park-issues#137]

**Comment by gdestuynder** [comment]
The cut over / transition is planned on July 15 IIRC @HerminaC

**Comment by gcoxmoz** [comment]
As I write this, there are 73 open issues in this repo, and the beta banner is still up on people.
Can we **not** be in a rush to take phonebook away, while the backlog of issues is reduced?

**Comment by gdestuynder** [comment]
@gcoxmoz most issues are not bugs or blockers, but I think @HerminaC is working on having a list of blockers. If there are blockers left I'm sure the date will change, until they're resolved.

**Comment by HerminaC** [comment]
@gcoxmoz I confirm. There is no blocker at this point, but for sure we'll not close down Phonebook if you find out any. There are mainly smallish bugs and feature requests. Our lead dev already solved quite a bit of them but he had PTO planned for this week and we've agreed not to deploy to prod before he left. You will see an updated version early next week.

**Comment by HerminaC** [comment]
I see your 'search by handle' request just now. makes sense, I'll prioritize it.

**Comment by globau** [comment]
While it has been the Mozilla thing to have duplicate systems online for extended periods of time (eg. mana/intranet), to avoid confusion please don't hesitate to pull the plug on the old phonebook as soon as dinopark leaves beta - even if it isn't 100% perfect.

**Comment by HerminaC** [comment]
Hey @gcoxmoz searching by handle should work now. Could you please try it? Thanks!

**Comment by gcoxmoz** [comment]
I see the issue from #138 as better, yes.  Good start.

**Comment by globau** [comment]
This redirect is in place - closing.

**Comment by gdestuynder** [comment]
hey thanks :D
