### ISSUE TITLE
phonebook functionality missing: search by handle

### ISSUE THREAD

**Issue by hwine** [mozilla-iam/dino-park-issues#138]
A critical (IMO) function of phonebook is absent in people.m.o: ability to search by "handle", especially bugzilla nickname.

Example - this works:
  https://phonebook.mozilla.org/?search/aryx
this does not:
  https://people.mozilla.org/s?query=aryx&who=all

I would consider this a blocker to #137

**Comment by dveditz** [comment]
agreed! I use this all the time. In fact it's one of my main uses of phonebook -- looking up IRC nicks or bugzilla "spam-bucket" emails to find the correct @mozilla.com address to send mail or a meeting invite.

**Comment by dveditz** [comment]
Aryx might be a bad example because there appears to be no/little data transfer from the old phonebook. Look at James Willcox instead: he's got "snorp" in 5 different fields (including all the ones I search for) but search still doesn't find it.

**Comment by globau** [comment]
related: #78, #130

**Comment by fiji-flo** [comment]
If you change your username (the [first field](https://people.mozilla.org/e?section=personal-info)) this will just work. In general people have a consistent username across resources we're working on supporting different usernames without yielding irrelevant search results like phonebook.
I see that we need to encourage people to set their username.

**Comment by hwine** [comment]
> If you change your username (the [first field](https://people.mozilla.org/e?section=personal-info)) this will just work. 

No - that is neither a) sufficient nor b) should be necessary. We want the tool to conform to the user, not make the user conform to the tool.

> In general people have a consistent username across resources we're working on supporting different usernames without yielding irrelevant search results like phonebook.

@fiji-flo I think you may not be understanding the problem we're reporting. People *do not have a consistent username* in this case. There are (at least) the following user names all of which *can* be different. 
- official ldap name (eg {first_initial}+{last_name}@m.c)
- ldap alias (eg ten_xer@m.c)
- slack alias (whatever they want)
- irc alias (whatever they want)
- bugzilla email (very often neither of the ldap emails)
- bugzilla nick (a convention - multiple allowed)

While phonebook's search can be overly broad, it does support these features, which many of us rely upon. False positives can be filtered (by search in page, or by eye). False negatives can not be worked around, and are search failures.

**Comment by globau** [comment]
> In general people have a consistent username across resources we're working on supporting

unfortunately this isn't always possible.  for example i'm `glob` most places, but i'm `globau` on github as someone else took `glob` (and did nothing with it ☹️).

https://phonebook.mozilla.org/?search/globau finds me on the current phonebook

**Comment by fiji-flo** [comment]
@hwine I get your problem. I do. I'm fiji-flo on github fiji in most places and fiji_flo on twitter and other things that don't allow dashes.

As I said we're working on this and it has high priority. Some of this is straight forward and just work some of this is tricky since we build on top of a strict schema provided by [cis](https://github.com/mozilla-iam/cis/) without any meta information. Verified GitHub for example does not just work with a username, since it's changeable and reusable, however there's way to make it work and I expect this to be done end of the week.

Thanks for the feedback so far and sorry if my initial answer sounded harsh. I usually stick to replying in the evening, which hopefully produces better answers.

**Comment by HerminaC** [comment]
@hwine @globau @dveditz
We're going to index github, bugzilla, slack and irc so that they are searcheable by default by the end of the week. 
Please bear with us for a little bit more and sorry about this. Thanks.

**Comment by globau** [comment]
looks like this has been fixed - https://people.mozilla.org/s?query=globau&who=staff now finds me.

thanks!

**Comment by hwine** [comment]
My use cases also now work!!! :tada:

Thanks so much!!!!
(@HerminaC I'll let you or @fiji-flo close, in case you want to track it somehow.)

**Comment by viorelaioia-zz** [comment]
Closing this, as it was fixed.
