### ISSUE TITLE
Allow search by keywords field

### ISSUE THREAD

**Issue by mjzffr** [mozilla-iam/dino-park-issues#142]
I often use phonebook to find people who specialize in a certain area, e.g. graphics, layout, automation. Sometimes this is info is mentioned in bio/description, which is already searchable, but the keywords field is even better for this purpose.

**Comment by fiji-flo** [comment]
you can search right now for [tags:Rust](https://people.mozilla.org/s?query=tags%3ARust&who=staff) (must be exact match or [tags:rust~1](https://people.mozilla.org/s?query=tags%3Arust~1&who=staff) (for one off). We're working on the UI for that.
