### ISSUE TITLE
adding a github account is impossible when using containers

### ISSUE THREAD

**Issue by escapewindow** [mozilla-iam/dino-park-issues#144]
In theory, I would add my `escapewindow` github account to my pmo page.

1. Open people.mozilla.org in a `Work` container, where it is set to open by default
2. `Identity -> add identity -> github -> verify`
3. This opens a github page in my `Github` container, where it is set to open by default
4. Then this opens an Auth0 page in my `Work` container, where it is set to open by default
5. This opens the front people.mozilla.org page
6. Check my account; my Github account is not linked.

This workflow won't work for people who have their github account in another container. Can we add support for that?

**Comment by fiji-flo** [comment]
@escapewindow I tried to reproduce this in a clean Firefox profile (67). And for me this exact flow worked. Can you please try this again. If possible look at the console if something shows up and tell me at what time you did it, to check our logs.
My personal setup is quite similar. Just to rule out that there's a not another issue you could try it in a private window.

**Comment by escapewindow** [comment]
The private window worked, thanks!
