### ISSUE TITLE
orgchart shows person who left, not found by search (stale orgchart?)

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-iam/dino-park-issues#147]
The org chart lists at least one person not found by search results.

Steps to reproduce:
1. Open the org chart.
2. Expand it.
3. Search for "Kathleen".
Actual result: 3 "Kathleen"s.

4. Search for "Kathleen".
5. Restrict to Staff.
Actual result: 2 exact matches

phonebook.mozilla.org also shows that the person has left.

**Comment by devinreams** [comment]
As another data point: our most recent interns are also correctly inactive/disabled in Workday but still appearing in People (see: Michelle reporting to Devin Reams, Yuval reporting to Sandy Sage).

**Comment by fiji-flo** [comment]
Thanks for reporting this. We had an issue with deleting people from the orgchart after a library upgrade. All interns and other people who left are deleted now.
