### ISSUE TITLE
Profile edit : Pronouns field intermittently missing content

### ISSUE THREAD

**Issue by gene1wood** [mozilla-iam/dino-park-issues#148]
When visiting the https://people.mozilla.org/e?section=personal-info page, intermittently the value for the `Pronouns` field is absent

I visited the URL above to edit my profile and the page rendered like this

![peoplemozillaorg-pronoun-field-missing](https://user-images.githubusercontent.com/1134034/62875353-bf995b80-bcd7-11e9-858b-b27a65318ea7.png)

then I re-navigated to the page and it rendered correctly like this

![peoplemozillaorg-pronoun-field](https://user-images.githubusercontent.com/1134034/62875379-c9bb5a00-bcd7-11e9-98e8-9d634d420000.png)

**Comment by gdestuynder** [comment]
I was not able to reproduce this - @viorelaioia @fiji-flo @andrew-sunada  have you seen this before or have an idea of what causes it?

Otherwise, we may request an HAR

**Comment by gdestuynder** [comment]
@gene1wood can you reproduce this in private browsing mode as well?

**Comment by gene1wood** [comment]
I've not tried. I can attempt it tomorrow and let you know.

**Comment by gene1wood** [comment]
I tried it a few times in private browsing but didn't trigger the bug. I did however notice that this bug likely affects both the Pronouns field and the Location field.

When the page is rendered both these fields are rendered after everything else as if they're assembled by some different backend call than the other elements. You can see the delay in this video showing how the page renders (in slow mo).

So I'd recommend focussing on the code that pulls in Pronouns and Location to see how those fields differ from the others.

https://youtu.be/y4kY2HyoZrQ
