### ISSUE TITLE
Please update 'Reports to' for 4 employees

### ISSUE THREAD

**Issue by tobinmori** [mozilla-iam/dino-park-issues#155]
Peter Bengtsson
Ryan Johnson
Gregor Weber
Schalk Neethling

All report to:
Tobin Mori

Thank you!

**Comment by fiji-flo** [comment]
Hi, they are still reporting to someone else in workday, it will be updated as soon as the structure changed officially. Please contact peopleops for this. I'll delete this issue as it contains names if that's alright.
