### ISSUE TITLE
Unable to save edits for any of my information

### ISSUE THREAD

**Issue by k88hudson** [mozilla-iam/dino-park-issues#156]
When trying to edit my information on https://people.mozilla.org/e?section=accounts, 
I get the message `A problem occurred, please try again later.` when trying to save.

I see the following error in the console:

```
TypeError: t is undefined.       app.js:1:72401
    handleDocumentClick https://people.mozilla.org/js/app.js:1
    handleDocumentClick self-hosted:1019
```

This is using Firefox Nightly 71.0a1 (2019-09-10) on Mac.

**Comment by HerminaC** [comment]
Hi Kate,

This is solved now, please try again.
And sorry about that.

Hermina

**Comment by k88hudson** [comment]
Thanks for the quick response! It is now working 👍
