### ISSUE TITLE
Getting a blank white screen when I try to navigate to https://people.mozilla.org/

### ISSUE THREAD

**Issue by RosanneScholl** [mozilla-iam/dino-park-issues#158]
The title says almost all. I have internet access, am on Nightly 70.0.a1 on a MacBook Pro with 10.14.6 and when I go to https://people.mozilla.org/ I get a blank white page even after reloading several times. This has happened before, and then later in the day it will work.

**Comment by RosanneScholl** [comment]
5 minutes later, now it works. It quickly goes to my SSO screen, logs in, and then to the directory. But this has repeated enough times that I'm confident it indicates an actual problem.

**Comment by RosanneScholl** [comment]
This is happening again today- at around 11 am and then again just now at 2:15. I have't been able to use the page at all today.

**Comment by ghost** [comment]
This is true for me as well.  It seems to think I have NoScript enabled, but I do not.  Nor do I believe that I have any NoScript-like addons enabled (disabled uBlock Origin for this)
`<strong>We're sorry but the Mozilla People Directory doesn't work properly without JavaScript enabled. Please enable it to continue.</strong>`

**Comment by HerminaC** [comment]
@fiji-flo @LeoMcA - could any of you guys please have a look into this when back? Thanks!

**Comment by LeoMcA** [comment]
This is hard to debug without being able to reproduce it. If this happens again, can you open the [web console](https://developer.mozilla.org/en-US/docs/Tools/Web_Console/Opening_the_Web_Console) and paste any error messages which get spit out (or email them to me [leo@mozilla.com] if they contain private information).

**Comment by ghost** [comment]
Sorry for the slow response. 

I get the following non-verbose error in a fresh Firefox profile.
Error: chunk-vendors.900ac52f.js:7:93068

I get a few more errors in my more aggressively customized main Firefox profile:
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). onloadwff.js:71:802491
The Components object is deprecated. It will soon be removed. people.mozilla.org
Error: chunk-vendors.900ac52f.js:7:9306

I get a chunk-vendor error with a longer stack track in Edgium:
Uncaught (in promise) Error: GraphQL error: profile does not exist
    at new e (chunk-vendors.900ac52f.js:7)
    at chunk-vendors.900ac52f.js:7
    at chunk-vendors.900ac52f.js:7
    at Set.forEach (<anonymous>)
    at chunk-vendors.900ac52f.js:7
    at Map.forEach (<anonymous>)
    at t.broadcastQueries (chunk-vendors.900ac52f.js:7)
    at chunk-vendors.900ac52f.js:7
    at Object.next (chunk-vendors.900ac52f.js:33)
    at g (chunk-vendors.900ac52f.js:33)
