### ISSUE TITLE
[Bug] Appears you can copy people's profile information to your own profile.

### ISSUE THREAD

**Issue by amychurchwell** [mozilla-iam/dino-park-issues#160]
## Steps to recreate.

1. Go to your profile and select 'edit' button.
2. Scroll to bottom and click on another profile from the "Colleagues" list.
3. Click back button in browser.

**Bug:** displays option to seemingly edit another person's profile.

<img width="1036" alt="Screen Shot 2019-10-25 at 7 56 53 AM" src="https://user-images.githubusercontent.com/30483988/67581560-0f939600-f6fd-11e9-9f36-aa1a6e07f02b.png">

If you attempt to edit the profile, if the original profile did not set a username there is an error of:
`Username must only contain letters from a-z, digits from 0-9, underscores or hyphens.`
or if they have set a username the error is:
`Username already exists. Please choose another one.`

which leads me to believe it is copying the profile information into your own.

**Comment by LeoMcA** [comment]
Indeed, but thankfully it doesn't look like it's revealing any private data, and if you do then go ahead and click save it writes to your profile.

This is still a weird bug, thanks for finding it!
