### ISSUE TITLE
Picture Upload: Privacy notice checkbox not nicely aligned

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla-iam/dino-park-issues#161]
Browser: Firefox Nightly from a few days ago

Steps to reproduce:
* Edit your profile
* Edit the picture - notice the misalignment of the checkbox once the dialog comes up

<img width="644" alt="Screenshot 2019-10-30 at 12 21 24" src="https://user-images.githubusercontent.com/330324/67854174-c5991e80-fb07-11e9-9462-e9ce0aac26e4.png">

**Comment by fiji-flo** [comment]
https://github.com/mozilla-iam/dino-park-front-end/pull/496

That fixes it, need to triple check that it doesn't break anything. Wondering why that was there.
