### ISSUE TITLE
Picture Upload: resulting image can't be found

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla-iam/dino-park-issues#162]
Steps to reproduce:
* Upload and size picture
* Check the privacy checkbox
* Click "Select"
* Notice that the image is correct in the preview
* Save profile
* Observe that on the profile the image can't be found

<img width="644" alt="Screenshot 2019-10-30 at 12 21 24" src="https://user-images.githubusercontent.com/330324/67854290-f416f980-fb07-11e9-92d4-060a11ce42be.png">

<img width="688" alt="Screenshot 2019-10-30 at 12 21 30" src="https://user-images.githubusercontent.com/330324/67854297-f8dbad80-fb07-11e9-851e-9dbb1a7a2e5e.png">

<img width="886" alt="Screenshot 2019-10-30 at 12 21 41" src="https://user-images.githubusercontent.com/330324/67854322-fed18e80-fb07-11e9-955d-dd777d958aad.png">

<img width="1451" alt="Screenshot 2019-10-30 at 12 21 51" src="https://user-images.githubusercontent.com/330324/67854328-02fdac00-fb08-11e9-9cfe-b5b8c84c956a.png">

**Comment by fiji-flo** [comment]
Thanks, that's a know issue I was about to file here. If you change the display setting to something that includes your scope (i.e. NDA'd) you'll be able to see the picture.

**Comment by MichaelKohler** [comment]
could it be that it just takes a while to process? I didn't do anything and now I can see it.

**Comment by yamamashakaa** [comment]
I had the same problem, then after reading the comments here I realized that changing the scope will let me see my picture. But I think that whatever the scope is I should be able to see my own picture. Also, for me the icon to change the scope was not clear .

**Comment by MilindaLaknath** [comment]
Had the same issue and set the scope to the public, then the image appeared. I think something wrong with the "staff" scope. When I set the scope to the "staff", image didn't appear even if I use the "view as staff" option.

**Comment by spoji** [comment]
I can reproduce this same issue. I had to change the scope to "NDA" to get my avatar to appear properly.

Keeping the scope to "Staff" was resulting to a broken image.

Tested under Chrome 77.0
