### ISSUE TITLE
Profile Edit: Accounts select boxes overlap with sidebar

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla-iam/dino-park-issues#163]
Steps to reproduce:

* Edit your profile
* Edit the accounts
* Click on the type of account and notice that part of the select is behind the sidebar

<img width="619" alt="Screenshot 2019-10-30 at 12 28 02" src="https://user-images.githubusercontent.com/330324/67854541-6e477e00-fb08-11e9-98f9-92abd218eb96.png">

**Comment by fiji-flo** [comment]
Confirmed. Addressed in https://github.com/mozilla-iam/dino-park-front-end/pull/495
