### ISSUE TITLE
Forbidden Page: "Link in footer" - Why not link it?

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla-iam/dino-park-issues#165]
The page at https://people.mozilla.org/forbidden says "Please submit all bugs or issues to the project's GitHub issue repository (link in footer)." Is there a reason why that is not directly a link?

<img width="810" alt="Screenshot 2019-10-30 at 12 33 14" src="https://user-images.githubusercontent.com/330324/67854918-43a9f500-fb09-11e9-857c-849034cb6d56.png">

**Comment by LeoMcA** [comment]
Not that I'm aware of, thanks!

**Comment by HerminaC** [comment]
@MichaelKohler no good reason, just a miss on our side. Thanks for noticing.
@LeoMcA do you think you could please update that by adding [this link](https://github.com/mozilla-iam/dino-park-issues/issues) directly in there? 
Thanks!

**Comment by LeoMcA** [comment]
@HerminaC I just [deployed a fix](https://github.com/mozilla-iam/dino-park-front-end/pull/547#issuecomment-571103681) to prod :)
