### ISSUE TITLE
Profile Edit: Phone number field does not allow inclusion of extension #

### ISSUE THREAD

**Issue by sharonbautista** [mozilla-iam/dino-park-issues#166]
The phone number field does not appear to allow inclusion of an extension number. There is also no separate field to add an extension, which is part of Mozilla space phone numbers and Mozilla soft phone numbers used by remotees.

Screenshot of error when extension is included:

<img width="663" alt="image" src="https://user-images.githubusercontent.com/17853015/67874440-eca12180-fb02-11e9-9b6d-82f357d1cfbe.png">

**Comment by fiji-flo** [comment]
Do you know if there's a standard for this which works with `tel:` links? We restrict numbers that the links work on your mobile.
