### ISSUE TITLE
Profile editor: Keys section without functionality, weird UX

### ISSUE THREAD

**Issue by jens1o** [mozilla-iam/dino-park-issues#168]
![image](https://user-images.githubusercontent.com/11234139/67877896-b67f9400-fb3a-11e9-95b0-b0ab120d50f3.png)
Could you consider adding a paragraph about what I can do with it?

Furthermore, it should be noted that when clicking on `Add / Remove`, it is without functionality for users without LDAP access, getting a prompt to enter a e-mail and a password.

**Comment by Mte90** [comment]
I can confirm the issue, isn't clear what is.

**Comment by LeoMcA** [comment]
@jens1o @Mte90 this should now be fixed (you might need to do a hard refresh), can you confirm?

**Comment by Mte90** [comment]
There is a box where is written that is required an ldap account now :-)
