### ISSUE TITLE
SSO: Mozilla People Directory appears twice, labeled "Phonebook" and "Mozilla People Directory"

### ISSUE THREAD

**Issue by jens1o** [mozilla-iam/dino-park-issues#169]
![image](https://user-images.githubusercontent.com/11234139/67878104-11b18680-fb3b-11e9-9b3e-6221a8c6f2c6.png)
(both link to people.mozilla.org)

**Comment by LeoMcA** [comment]
This is a bit of a hack to allow people to search for "People Directory" or "Phonebook" and reach PMO.
