### ISSUE TITLE
Can I edit my profile? 

### ISSUE THREAD

**Issue by LucyeoH** [mozilla-iam/dino-park-issues#17]
I wanted to hide my phone number (I really don't want people to call me :)) 

I expected to be able to edit my profile by clicking "my profile" in the menu but that didn't work. 

Is the edit feature not available yet?

**Comment by mbransn** [comment]
@LucyeoH good flag and very much a [feature we're working toward](https://screenshots.firefox.com/YbFxw5XCJv4PPaNk/web-mozillians.dinopark.infra.iam.mozilla.com). Currently, Phone number visibility provides feature parity with Phonebook, where staff members are able to see eachother's phone numbers.

> I expected to be able to edit my profile by clicking "my profile" in the menu but that didn't work.

Our next update will include the ability to edit your profile and set the visibility of your content by field; e.g. you will be able to hide your phone number from public view. Your intuition was correct btw, clicking on 'My Profile' will indeed enable to to view _and_ edit your profile in the future release.

cc @hmitsch if I've missed something critical here

**Comment by hmitsch** [comment]
The only thing I'd like to add: 
This kind of data availability is the reason for our "double auth wall" which ensures that only Staff have access to DinoPark at this moment.
