### ISSUE TITLE
Too many fields as only for staff as default

### ISSUE THREAD

**Issue by Mte90** [mozilla-iam/dino-park-issues#172]
If the purpose of this website is reach people there are too many fields (like also avatar) with as default only staff.

Often people don't think of visibility only later so it is better to change like for registered only or for public and later let the user to change but avoiding to do that in all of them, that is kind of boring.

**Comment by LeoMcA** [comment]
My understanding is this is a technical limitation, if fields didn't default to staff then we'd unintentionally leak data from Auth0 without explicit user consent.

**Comment by Mte90** [comment]
Well there are some data can be configured for registered users because in my case I am a volunteer and not staff.
