### ISSUE TITLE
Grey text is not very easy to read

### ISSUE THREAD

**Issue by Mte90** [mozilla-iam/dino-park-issues#173]
Also the Firefox accessibility test confirm the issue

![immagine](https://user-images.githubusercontent.com/403283/67938423-b8dffd80-fbcf-11e9-985b-2f7f1a0a4369.png)

**Comment by LeoMcA** [comment]
Good catch, thanks!

**Comment by LeoMcA** [comment]
This has been fixed on testing and should be hitting production in the next few days

**Comment by LunarTwilight** [comment]
Looks like this is in production so should this issue be closed now?
![image](https://user-images.githubusercontent.com/13520392/73603832-541ca200-4534-11ea-84db-8dc104128864.png)

**Comment by jens1o** [comment]
Closing as fixed.
