### ISSUE TITLE
Missing external accounts

### ISSUE THREAD

**Issue by Mte90** [mozilla-iam/dino-park-issues#174]
One of the key features of mozillians is that is easy to reach people because all the links for socials are available in case the person is not available on others.

This is missing...

**Comment by Mte90** [comment]
I saw in other profile that they are using accounts but for us there are only 3 options...

**Comment by LeoMcA** [comment]
Does the biography work for this?

**Comment by Mte90** [comment]
Well this means break a lot the UI because the bio become very log like mine https://people.mozilla.org/p/Mte90
Also there is already the Accounts section that suggest people to fill it, if we ask to fill the bio they probably will never add them.

**Comment by LeoMcA** [comment]
> Also there is already the Accounts section that suggest people to fill it, if we ask to fill the bio they probably will never add them.

Yeah that's true, I hadn't considered this.
