### ISSUE TITLE
Validate languages and make clicking on languages take you to searching for that language

### ISSUE THREAD

**Issue by Mte90** [mozilla-iam/dino-park-issues#175]
Mozillians has the list of languages to help on writing and avoid this kind of things

![immagine](https://user-images.githubusercontent.com/403283/67938805-808cef00-fbd0-11e9-8e35-eab5b6018339.png)

Also because it was possible (with a pr that I did and abandoned  because of this project) to filter people by languages spoken (very helpful for communities).

**Comment by LeoMcA** [comment]
I don't think we want to limit the languages a user can add here, @HerminaC can you confirm?

> filter people by languages spoken

You can search for people with a particular language tag with the `language:` modifier, eg: https://people.mozilla.org/s?query=languages%3A%22British%20English%22&who=all

**Comment by Mte90** [comment]
It is not clear because the languages are not clickable.

About the languages right now in mozillians it is a defined list to avoid also the kind of things I did.

**Comment by HerminaC** [comment]
Hey @Mte90 ,

Indeed, this could be implemented in a nicer way. Thanks for bringing it to our attention, will file a ticket but we'll probably get to it later as we're now quite swamped with our roadmap and we're mainly addressing bugs or very annoying things, which this is not.

Thx,
Hermina

**Comment by Mte90** [comment]
The point is not only a clickable link but there is no validation of what I am writing.

I can write whatever I want there and maybe alter also the link that will be added.
