### ISSUE TITLE
No validation in accounts

### ISSUE THREAD

**Issue by Mte90** [mozilla-iam/dino-park-issues#176]
![immagine](https://user-images.githubusercontent.com/403283/67938927-c1850380-fbd0-11e9-952d-4b99ad149773.png)

As You can see there is no validation like for spaces like it is on mozillians

**Comment by LeoMcA** [comment]
We probably want to at least trim whitespace either side so that users aren't taken to links like `https://discourse.mozilla.org/u/%20username`
