### ISSUE TITLE
Wish adding tags could be easier

### ISSUE THREAD

**Issue by devcer** [mozilla-iam/dino-park-issues#177]
Adding tags or languages or any other section is harder.
-> First click on Edit
-> Click on Add Tag
-> Type tag
-> Either press enter or click submit
-> Then again click Add tag to add another tag

Could have been more easier if the flow is similar to mozillians.org!

**Comment by jens1o** [comment]
see also https://github.com/mozilla-iam/dino-park-issues/issues/134#issuecomment-548298112
