### ISSUE TITLE
Linking to Bugzilla fails

### ISSUE THREAD

**Issue by MeFisto94** [mozilla-iam/dino-park-issues#182]
When trying to add my Bugzilla Identity, I see the rainbow dinosaur (https://bugzilla.mozilla.org/mojo/failraptor.png).
This happens after confirming bugzilla as oauth(?) application with the permission user:read.
As soon as I confirm that dialog, I see the dinosaur.

Unfortunately I cannot provide any helpful information other than that

**Comment by HerminaC** [comment]
Thanks @MeFisto94 !
@LeoMcA @fiji-flo guys, do you think you could please have a look into this?

**Comment by LeoMcA** [comment]
I got the same issue, then I cleared my cookies on bugzilla.mozilla.org, went through the process again (having to log in this time) and it worked - so I'm almost certain this is a bugzilla issue.

**Comment by fiji-flo** [comment]
We saw these issues earlier this year and they where gone for a while. Looks like it got worse again. I reported a bug in BMO. Feel free to follow / comment there.

* https://bugzilla.mozilla.org/show_bug.cgi?id=1604852
* https://bugzilla.mozilla.org/show_bug.cgi?id=1557735

**Comment by gdestuynder** [comment]
@dklawren (just making sure you've seen this)
