### ISSUE TITLE
cannot login to people

### ISSUE THREAD

**Issue by wrosenauer** [mozilla-iam/dino-park-issues#186]
I've got an LDAP account as contributor but when I try to login to people.mozilla.org it tries a 2nd factor auth and then tells me that my account cannot authenticate using DUO.

**Comment by HerminaC** [comment]
@gdestuynder do you think you could please have a look into this? Thanks!

**Comment by gdestuynder** [comment]
Hi, if you've never done so you need to setup your 2FA on https://login.mozilla.com

Note that this also means you have not used this account in years - if it is no longer used you can  request for it's deletion on https://bugzilla.mozilla.org/enter_bug.cgi?product=Infrastructure%20%26%20Operations&component=Infrastructure%3A%20LDAP
