### ISSUE TITLE
Update Accounts to include Matrix

### ISSUE THREAD

**Issue by gcoxmoz** [mozilla-iam/dino-park-issues#189]
With IRC going away and Matrix coming up, please consider updating the Accounts choices to reflect this.

**Comment by freaktechnik** [comment]
This seems to have been added, however it would be really nice if it also linked to matrix.to for that user.

**Comment by gcoxmoz** [comment]
Oh.  Guess they did.  Well spotted.

**Comment by LunarTwilight** [comment]
hm how would this work with users who don't give a full username (eg, `@example.host.tld`)? Maybe assume `@username:mozilla.org` if they just put a username?

**Comment by LunarTwilight** [comment]
Also until/unless federation gets set up, I don't think matrix.to links will work, so it might be better to use chat.mozilla.org links instead?

**Comment by freaktechnik** [comment]
They do work. The main issue with matrix.to links is that they will refer to riot.im as riot instance, while most people use chat.mozilla.org as their riot instance. Federation has nothing to do with what client you can use, it only affects servers talking to each other.

**Comment by tomer** [comment]
> The main issue with matrix.to links is that they will refer to riot.im as riot instance, while most people use chat.mozilla.org as their riot instance.

There should be possible to link directly to `chat.mozilla.org` instance. For example, my profile should be something like https://chat.mozilla.org/#/user/@tomer:mozilla.org 

Another option could be to host the `matrix.to` application with `riot.im` links replaced with `chat.mozilla.org`. ([source code is available here](https://github.com/matrix-org/matrix.to))

**Comment by freaktechnik** [comment]
> There should be possible to link directly to chat.mozilla.org instance. For example, my profile should be something like https://chat.mozilla.org/#/user/@tomer:mozilla.org

The tradeoff with using chat.mozilla.org links (which seems to be Mozilla's current strategy, so probably what this should do for now), is that they only work on desktop if the user is signed in to mozilla's riot instance. Same applies to a self-hosted matrix.to instance, since the link handling from Riot on Android for example won't capture it.

It sounds like matrix.to is going to be reworked soon-ish to be more user friendly and allow for things like surfacing a custom riot instance.

**Comment by tomer** [comment]
> The tradeoff with using chat.mozilla.org links (which seems to be Mozilla's current strategy, so probably what this should do for now), is that they only work on desktop if the user is signed in to mozilla's riot instance. Same applies to a self-hosted matrix.to instance, since the link handling from Riot on Android for example won't capture it.

At the moment, the Mozilla Matrix field is plaintext, so people have to manually search for the user. Linkning directly to `chat.mozilla.org` will provide **some** users to enjoy this feature, while `matrix.to` provides similar link (but not using the mozilla domain) but provide instructions for other clients (at the moment Weechat, Quaternion and Tensor in addition to riot.im).

Another option, which is even worse in my opinion, could be to use `mx://` links, and ask users to register an handler (navigator.registerProtocolHandler) upon connecting to `chat.mozilla.org`.

**Comment by gcoxmoz** [comment]
I should've closed this back when the field got added.  The rest of this isn't in line with my request.
