### ISSUE TITLE
"Mozillians" still used in a bunch of places to describe the site

### ISSUE THREAD

**Issue by geroter** [mozilla-iam/dino-park-issues#19]
The word "Mozillians" is still used in a few places to describe the site.

For example:
1)  <title>Mozillians</title> in the <head>
2) <noscript>
      <strong>
        We're sorry but Mozillians doesn't work properly without JavaScript enabled. Please enable it to continue.
      </strong>

I couldn't find any more, but maybe easy to search around.

**Comment by hidde** [comment]
Thanks @geroter, they were indeed the last two places where we still used it, not counting the README. I have removed both, this change is now live.
