### ISSUE TITLE
Search terms altered if authentication necessary for search from search plugin

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-iam/dino-park-issues#191]
1. The people.mozilla.org search engine is installed in the browser (Firefox Nightly) from the browser's search bar.
2. A keyword has been assigned to the search engine (Options > Search).
3. A search in the people directory gets started from the browser's address bar.

Since today or yesterday (might not have search Saturday and Friday), searches get the search term changed if the auth0 authentication has to be renewed (I always get a search for 'rediger').

**Comment by badboy** [comment]
Delete the cookie named `request_uri`.
Known problem, I think @fiji-flo is still trying to work around it.

**Comment by Pike** [comment]
On which domain is that cookie? I had already cleared the cookies on people, to no avail.

**Comment by jld** [comment]
I've been having this problem (with a keyword bookmark in Firefox) and there's a `request_uri` cookie for the domain `.people.mozilla.org` (note the leading dot) with the old/wrong search I keep being redirected back to, and one for the domain `people.mozilla.org` (without leading dot) with the correct last search.  I've deleted them (tried to delete the first one only, but Firefox deleted both) and I'll see what happens next time.
