### ISSUE TITLE
weird characters in title when viewing open tabs (Firefox Windows)

### ISSUE THREAD

**Issue by cshields** [mozilla-iam/dino-park-issues#193]
There are character placeholders that show up in the tabs view of firefox (windows taskbar) which are not reflected in the actual title of dinopark - but only with dinopark:

![image](https://user-images.githubusercontent.com/225283/73778284-ef8e5c80-4758-11ea-93bc-cdd282def273.png)

**Comment by Archaeopteryx** [comment]
Not seeing them in the tabs here but in the task bar. The leading character returns `8296` for `charCodeAt`. That's Unicode Character 'FIRST STRONG ISOLATE' (U+2068)

Seems to be a regression from the migration to Fluent https://github.com/mozilla-iam/dino-park-front-end/commit/3e8d1beb75d0beb7b94ff8bde47246f9b972d960

**Comment by cshields** [comment]
Yeah, to clarify I only see it in the tab list within the task bar.  (tab bar.. task bar.. tab in task bar..  *headdesk*)
