### ISSUE TITLE
I got an error message 

### ISSUE THREAD

**Issue by LucyeoH** [mozilla-iam/dino-park-issues#20]
When I tried again it worked but the first time I searched for Andreas this is what I saw. 

<img width="1078" alt="screen shot 2018-11-27 at 2 42 17 pm" src="https://user-images.githubusercontent.com/8070833/49161476-e4d76c80-f2f6-11e8-840a-723d7069ff13.png">

**Comment by akatsoulas** [comment]
This should be fixed with the latest release. @LucyeoH can you try again this search to verify if this is working for your profile?
