### ISSUE TITLE
ICC color profiles are stripped from profile photo uploads (without sRGB conversion)

### ISSUE THREAD

**Issue by floatingatoll** [mozilla-iam/dino-park-issues#200]
When uploading a profile photo that uses ICC colorspace "Display P3", Dinopark simply strips the ICC profile without converting the image to sRGB. This results in damaged profile photos for anyone uploading photos from a wide color pipeline - such as modern mobile phones, DSLR cameras, or any Apple devices.

Please either retain the ICC profile included with the user's uploaded image, or convert the uploaded image to sRGB ('relative colormetric') prior to stripping the ICC profile from the image.

An example of this issue can be viewed on my profile page, where I uploaded a P3-tagged image and the image currently displayed demonstrates RGB values from the P3 colorspace but is displayed incorrectly in Firefox due to its assumption that untagged images are sRGB. I am available on Slack to help support analysis and repair of this issue.

**Comment by floatingatoll** [comment]
We looked into this a bit and after reviewing https://github.com/mozilla-iam/dino-park-fossil/blob/master/src/send/resize.rs#L24 I tested my raw (unresized) profile image - it is delivered with correct ICC profile and looks fine in Firefox - but all resized versions end up with missing data.

**Comment by fiji-flo** [comment]
I dug deeper. Just to confirm the _raw_ imaged retrieved from the API had a sRGB (default) color profile but it should have been P3, so it's not the resizing (sorry I got confused there).

I reduced it to this, save that and have a _P3_ image called `i.jpg` next to it. If you right click → save the first image it should still have the color profile, right click → save the 2nd image it's missing. I'll try to figure out what a browser does when drawing on a canvas but I'd hope they convert.

```html
<body onload="draw()">
    <img src="i.jpg" />
    <canvas></canvas>
    <script>
        function draw() {
            const canvas = document.querySelector('canvas');
            const img = document.querySelector('img');
            canvas.width = img.width;
            canvas.height= img.height;
            const ctx = canvas.getContext('2d');
            ctx.drawImage(img, 0, 0);
        }
    </script>
</body>
```

**Comment by floatingatoll** [comment]
I suspect it converts to "whatever colorspace the canvas element is using", which _may_ vary per browser, and (in Firefox's case) I believe also per ICC about:config settings (gfx.color_management). There's a web standard (WIP: [CSS color level 4](https://www.w3.org/TR/css-color-4/)) that essentially states "sRGB unless specified otherwise" that will help resolve the inconsistencies, but Firefox continues to use the monitor-native colorspace for HTML by default instead of sRGB (this is most obvious with #ff0000 side-by-side with other browsers) — and so that _could_ includes canvas.

**Comment by floatingatoll** [comment]
Note that the raw image *does* have ICC included, while the resized images *do not* have ICC included — so it sounds like there are multiple steps where the color is being mutated. The raw, with its profile, is visually acceptable and does not have apparent issues.

**Comment by jens1o** [comment]
I looked into this the last two working days. Here is what I've come up with until here.
To get a first grasp for this bug, I was provided the image floatingatoll could reproduce with.
The sample image does actually *not* provide an ICC color profile (i.e., the png image does not include an `iCCP` chunk), but instead relies on the png `sRGB` auxillary data chunk to indicate its special color management. I was also able to reproduce this with an image that includes an `iCCP` chunk. Throughout my research, I figured that the library used was just missing to copy some metadata, but as atoll got back to me saying she could still reproduce (while my workaround had the same metadata information as the original image), I concluded that there *may* be is an actual bug inside the resizing algorithm I couldn't work-around for now myself (either way, I would have reported a bug, but when I was able to work-around the bug before-hand, I would already be able to file a pull request to fix the issue).

Hence, I filed an upstream issue and will look from there: https://github.com/image-rs/image/issues/1300

**Comment by jens1o** [comment]
A little bit of an update: My approach with copying metadata was good, I was just lacking to read the spec carefully enough. After a heads up from someone in the issue, the fix worked, as the spec says that the data I manually copied in in the downscaled images in the end must be put before the first image data (`IDAT`) chunk. A fix is coming.
