### ISSUE TITLE
Org chart hierarchy visuals

### ISSUE THREAD

**Issue by nukeador** [mozilla-iam/dino-park-issues#21]
Hi,

I find a bit challenging to visually see on the org chart when a team finish and the next one starts when you expand one of them.

_[screenshot removed to ensure privacy]_

In this screenshot I'm referring to the space between Vance Chen and Michael DeAngelo

**Comment by hmitsch** [comment]
Hi @mbransn,

I'd be interested to hear your thoughts on this.

Best regards,
   Henrik

**Comment by hmitsch** [comment]
PS: @nukeador and @lucyeoh, thanks for reporting this. That's exactly the type of feedback we are looking for!

**Comment by mbransn** [comment]
Thanks for the flag @hmitsch --  @nukeador @LucyeoH I echo the appreciation for the feedback as this is definitely a 'tough thing' to figure out design wise. 

We've gone through multiple iterations and will continue to fine tune as we gather this feedback and others through _demo table_ + _remote user testing_ + _in person user testing_. 

I'll ask for a small bit of patience as we start to work through some potential solutions to this following All Hands. I'd expect an update to land in production by our Milestone 2 release in early 2019. 
cc @flekkowich if I've missed anything.

**Comment by flekkowich** [comment]
A few add-ons to this problem I see:

1. The phonebook has very different symbols for manager and non-managers (arrow vs dots), they are different in size and they are different in colour which makes it easier to identify differences.

2. In phonebook the icons are a lot smaller, making them more guiding and they don't take over the hierarchy as much. 

3. The alternating colours currently help identify the different lines but also creates a secondary grouping beyond teams so it could be part of why we see this problem. 

I think it might be good to land something earlier on this but lets wait to make a final call after this week and we've seen usability research results and results from demo. Monday morning call? 

cc @mbransn

**Comment by LucyeoH** [comment]
I was going to file a new issue but realized it might be the same as this. In the org chart view by default it's partially "unrolled" for some people in that it shows their direct reports without you having to "open" them up. 

This is confusing because then it's not clear if they only have 1 direct report or whether you have to click to open them. So for example, I was trying to look up Nate Weiner and thought initially that there was some sort of mistake because it only showed one direct report. <img width="568" alt="screen shot 2018-12-10 at 2 19 37 pm" src="https://user-images.githubusercontent.com/8070833/49756586-4e0c9780-fc88-11e8-96ba-348f815ad147.png">

I was going to file it as a bug until I realized that you have to click to see the actual full list.

Hope this is helpful!  I know it's tricky

**Comment by hmitsch** [comment]
@LucyeoH can you "force reload" the site. We expand the 1-level of direct reports when you open a person who manages others. Does this not work for you?

-Henrik

**Comment by LucyeoH** [comment]
@hmitsch even when I just open the org chart without searching anyone it has some people are fully expanded, some people are partially expanded (only show 1 or 2 ppl) and some people fully rolled up. 

I.e. Mark Surman is fully expanded, Angela is partially expanded (only shows Ashley.... why?), Michael is fully rolled. 

<img width="611" alt="screen shot 2018-12-11 at 2 08 05 pm" src="https://user-images.githubusercontent.com/8070833/49823946-deadab00-fd4e-11e8-8028-dc8b61a04ab6.png">

**Comment by mbransn** [comment]
@LucyeoH the initial load of the org chart is showing our executive teams expanded. This was a UX decision to minimize the cognitive load when first viewing the org chart; e.g. having the org chart display fully expanded is hard to digest and showing just the top line executives is limiting. Our initial approach is to show Mitchell, Chris and Mark's direct reports, allowing people to 'dig in' to their respective team from there.

This is why in your screenshot Mark Surman is expanded to show is direct reports and Micheal DeAngelo is collapsed as he is part of Chris Beard's team. Angela is not expanded at all as she and Ashley are both at the same level on Mark's team, which is being displayed alphabetically.

In the future we're considering adding UI controls such as auto expand/collapse of the full chart as well as functionality for the chart to remember your expansion preferences. Hope this helps! @hmitsch can you remind us what the current shortcut for expand is?

@flekkowich agreed on your additional points re: what Phonebook tree UI currently does vs. what we've done in our first iteration. @rfirebaugh is currently exploring iterations based on testing feedback, previous iterations and your points.

**Comment by LucyeoH** [comment]
@mbransn ohhh it's really not clear visually that Angela and Ashley are on the same level. Which I think is the source of much of the confusion.

**Comment by mbransn** [comment]
@LucyeoH agreed! Working to solve with this exact issue. 😄 Stay tuned...

**Comment by mbransn** [comment]
Hi all, an updated version of the org chart has been sent for implementation today (see screenshot below). Reassigning this to @hidde so we can notify here when this v2 is on production.

*Primary changes to expect*:
- chevron arrow replaces +/- for entries with children
- bullet precedes any entry without children
- indentation has been increased to provide more distinction between levels as entries expand

_*note: design uses fake data to ensure privacy_
![org-chart-v2](https://user-images.githubusercontent.com/18686986/50026378-959f6600-ff9d-11e8-846d-8bd82dee0f2d.png)

**Comment by hmitsch** [comment]
> In the future we're considering adding UI controls such as auto expand/collapse of the full chart as well as functionality for the chart to remember your expansion preferences. Hope this helps! @hmitsch can you remind us what the current shortcut for expand is?

Sorry for the late reply, it's `[Alt]+click` to expand the node and all its subnodes.
On MACs the [Alt] key is the [Option] key.

**Comment by hmitsch** [comment]
These new designs look awesone, @mbransn!
