### ISSUE TITLE
Abbreviated first name struggles 

### ISSUE THREAD

**Issue by LucyeoH** [mozilla-iam/dino-park-issues#22]
[Caveat - Not sure if this is even a bug....]

I was trying to search for "Matt Grimes" but it returned no search results until I either removed "Matt" or typed in "Matthew". 

Might not be fixable but is confusing b/c some people go by the abbreviated versions of their names which makes it hard to find them in the people directory.

**Comment by hmitsch** [comment]
Need to discuss this with @akatsoulas and @fiji-flo.

**Comment by hmitsch** [comment]
Hi @LucyeoH,

the issue you reported is now solved. Please reach out if you observe other search issues.

Best regards,
   Henrik
