### ISSUE TITLE
Browser compabtibility: iOS v11.4 (was: Error messages on Search and Org Chart)

### ISSUE THREAD

**Issue by flekkowich** [mozilla-iam/dino-park-issues#23]
I'm finding that on mobile when I try to use Org Chart and Search i get errors

mobile iOS v 11.4
Safari and Chrome

Org chart:
visit: people.allizom.community
auto-login (already logged in once and worked on first log in). 
select Org Chart in top nav
Error: only shows one white stribe w/ copy "people who need their managers set"

Search
visit: people.allizom.community
auto-login (already logged in once and worked on first log in). 
Select search
Enter search term 
Error: served: This page isn't available Error Page.

**Comment by hmitsch** [comment]
Hi @flekkowich,

thanks for reaching out. You are using an old version of iOS. DinoPark is currently supporting _Evergreen Browsers_ only.

I suggest we wait for more feedback to see if we need to re-evaluate this decision.

Best regards,
   Henrik

**Comment by hmitsch** [comment]
DinoPark works after updating to the latest iOS. Closing issue.
