### ISSUE TITLE
A tag closed too late on officeLocation

### ISSUE THREAD

**Issue by hmitsch** [mozilla-iam/dino-park-issues#25]
<img width="558" alt="image" src="https://user-images.githubusercontent.com/869692/49370796-4ca90100-f6c3-11e8-808f-75a75fb7ca81.png">

Can we make it so that the time zone is _outside_ the link?

**Comment by hidde** [comment]
Fix for this is on the way in https://github.com/mozilla-iam/dino-park-front-end/pull/158

**Comment by hidde** [comment]
This is now fixed in prod!
