### ISSUE TITLE
 Org Chart from Profile view -> show expanded Org Chart from profile down

### ISSUE THREAD

**Issue by flekkowich** [mozilla-iam/dino-park-issues#28]
When clicking Org Chart from Profile view, show expanded Org Chart from profile down

Current:
Go to profile
Click Org Chart in Relations box
Show collapsed profile view

Future
Go to profile
Click Org Chart in Relations box
Show expanded profile view from source profile and down.

**Comment by hidde** [comment]
Thanks @flekkowich, great point! We've just shipped this. Managers are now pre-expanded when you view them in org chart (from ‘View in org chart’ on the profile, or from the search result).
