### ISSUE TITLE
Remove Phone Number from Contact Me Component

### ISSUE THREAD

**Issue by hmitsch** [mozilla-iam/dino-park-issues#29]
(from All Hands Demo)

Beta user feedback shows that people do not appreciate having their `phone number` in the _Contact Me_ component.
Let's remove it. :-)

**Comment by akatsoulas** [comment]
Is the phone number displayed in a less prominent position? Are we dropping this completely?

**Comment by hidde** [comment]
It is still shown on people's profiles, just not on the Contact Me shortcut.

**Comment by hmitsch** [comment]
Fixed in December. Closing issue.
