### ISSUE TITLE
UI Feedback: Names on Manages section in Relations Component

### ISSUE THREAD

**Issue by hmitsch** [mozilla-iam/dino-park-issues#32]
User feedback:
> Doing full list of names in the profile page's "this person manages" rather than just photos - scrubbing over tooltips takes awhile.  Would be ok if that was a thing I had to expand rather than expanded by default (bonus points if it saved my expanded state)

/cc @mbransn: I copied this issue here from our mail thread. Hope that's okay.

**Comment by mbransn** [comment]
Thanks @hmitsch -- I'd like to take this feedback, along with the relations naming feedback #39, and work through solutions with @rfirebaugh @flekkowich over the next week or so.

cc @hidde that this and org chart updates are our UX priority at the moment (alongside edit profile capabilities of course).

**Comment by hmitsch** [comment]
To anybody who reads this: Please upvote by pressing 👍 , if you want us to work on this.

@mbransn should we think about iterating on this for the APR25 Milestone?

**Comment by mbransn** [comment]
@hmitsch we do have designs already for UI controls that move between grid (picture only) and list (picture w/name & title) views. These have yet to be implemented and I'm unsure @hidde will get to it before APR 25 -- will let him speak to that.

Screenshots for reference:

<img width="698" alt="Screen Shot 2019-04-19 at 4 26 25 PM" src="https://user-images.githubusercontent.com/18686986/56447918-11008380-62c0-11e9-80bd-12047a4bfa87.png">

<img width="698" alt="Screen Shot 2019-04-19 at 4 26 48 PM" src="https://user-images.githubusercontent.com/18686986/56447938-165dce00-62c0-11e9-90a4-a3c969b2c20e.png">

**Comment by jofish** [comment]
Can I strongly vote for fixing this? And this is pretty key to what people need to do -- I don't see much value in having the picture only/grid version. It should at very least default to the list-with-name-and-pic verison. @mbransn. Thanks!

**Comment by hidde** [comment]
Thanks @jofish for your feedback. Just to give a status update, the list view is implemented and almost ready to go, it should land in the beta soon.

@mbransn any thoughts on making the list view default vs grid as default?

**Comment by mbransn** [comment]
Agreed this is important @jofish, thanks for checking in -- as @hidde mentioned this is indeed going to production very soon.

Regarding default view being `grid` vs. `list`: `grid` has been chosen as it takes up less vertical space for initial profile page discovery, esp on smaller devices. That said, the toggle back and forth will be persistent for a session (e.g. it will 'remember' if you've toggled to `list` and keep that as your preference on profile pages). The best way for us to determine how it _should default_ going forward will be based on actual usage feedback: how many people toggle to `list` and leave it there vs. how many switch back to `grid` and leave it there; or how many people agree with @jofish and leave us more comments like the above 😉; or further testing via remote testing and the like.
