### ISSUE TITLE
Add meaningful content to the <title> tag 

### ISSUE THREAD

**Issue by mathjazz** [mozilla-iam/dino-park-issues#34]
First of all, excellent work! The app is beautiful and a pleasure to work with, both on my phone and laptop. Can't wait to see it live!

The only thing that bothers me a little is the [`<title>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/title) tag, which doesn't display meaningful content on the [profile page](https://web-mozillians.dinopark.infra.iam.mozilla.com/beta/p/r--9sxwOb1MXgWLbI7hiDgp_g==) and when a person is selected from the [Org Chart](https://web-mozillians.dinopark.infra.iam.mozilla.com/beta/o/highlight/r--9sxwOb1MXgWLbI7hiDgp_g==).

**Comment by hidde** [comment]
Hello @mathjazz ! Thanks for your kind words and for filing this ticket.

It may not seem like it, but the `title` is actually optimised for those pages, according to this format:

* `username` - Profile - Mozilla Directory
* `username` - Org Chart - Mozilla Directory

(with username being the person's username. The attributes are in order of uniqueness. In the beta, some (a lot) of our users have randomly generated user names, I think this may be why it looks meangingless?

**Comment by mathjazz** [comment]
Oh, that makes sense. Thanks for the explanation!
