### ISSUE TITLE
Discourse category not available?

### ISSUE THREAD

**Issue by jklukas** [mozilla-iam/dino-park-issues#35]
When I click the link in the footer to give feedback (https://discourse.mozilla.org/c/iam/dinopark), I get an "Oops! That page doesn’t exist or is private" error message. Is there a separate permissions model for Discourse that I haven't been added to as a beta tester?

**Comment by hmitsch** [comment]
Hi @jklukas, you need to be logged in to Discourse. The category is currently access restricted to Staff & NDA'd Mozillians.

Best regards,
   Henrik

**Comment by jklukas** [comment]
Indeed. I don't use discourse on a regular basis, so totally missed that I wasn't logged in. Thanks.
