### ISSUE TITLE
Remove siblings in org chart

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla-iam/dino-park-issues#36]
Would be nice to be able to see someone’s chain of command more easily. I just deleted them from the DOM but would this be an interesting view?
<img width="648" alt="image" src="https://user-images.githubusercontent.com/68213/49764024-54a50a00-fc9c-11e8-81a8-c561fc022b23.png">

**Comment by hmitsch** [comment]
CC'ing in @mbransn @flekkowich, our design authorities.

**Comment by hmitsch** [comment]
This is a great idea, we will keep it on the backlog. If people like this, please upvote the issue by pressing 👍 .
