### ISSUE TITLE
Unclear where photos are being pulled from

### ISSUE THREAD

**Issue by jklukas** [mozilla-iam/dino-park-issues#37]
I changed my photo last week on Phonebook, but don't see the update in dino-park. It's unclear whether the photos were a one-time import from Phonebook or if they're coming from some other source. If it's going to be pulling from some other system long-term, it would be helpful to have some info on the page that indicates how to update photos.

**Comment by hmitsch** [comment]
We pull photos off Phonebook. Currently, we still do _manual imports/updates_. The next update will be early next week. 
We expect to switch to auto-updates early in the new year.

Best regards,
   Henrik
