### ISSUE TITLE
Allow full expansion of org chart

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-iam/dino-park-issues#38]
On phonebook, having the full org chart expanded and the full overview or people just a scroll is really speeding things up for me. It would be helpful if DinoPark had a button to expand the whole org chart.

**Comment by hidde** [comment]
@Archaeopteryx thanks for your feedback. 

Currently, it is actually possible to do a full expansion of an org node, by pressing `Alt` while you click the plus icon to expand. That will expand everyone that in the reporting chain for that person. 

This loads a lot of people and we can't guarantee excellent performance, but it should work.

Hope this helps!

**Comment by mbransn** [comment]
@Archaeopteryx +1 to what @hidde said, this is our expand functionality for beta. For future iteration we're working toward scope that includes expand/collapse UI, which should hopefully make usability more inclusive of all keyboard/mouse/track pad preferences.

**Comment by hmitsch** [comment]
This is in scope for our APR25 Milestone. Closing issue here, as we track this in our Jira tickets.
