### ISSUE TITLE
Org Chart Terminology: Relations feels awkward

### ISSUE THREAD

**Issue by hmitsch** [mozilla-iam/dino-park-issues#39]
Feedback from a beta user:
> "Relations" feels... awkward to me as a word.  It's technically correct but evokes familial connections
I'm not sure I have a better suggestion
> (context is the phonebook's "Relations" section)

**Comment by hmitsch** [comment]
I prefer `Colleagues` over `Teammates`. Should we give that a try in a release next week?

-Henrik

**Comment by mbransn** [comment]
Hi @hmitsch, talked over this with @flekkowich @rfirebaugh -- good to use `Colleagues` in place of `Relations`. We'll also change this in the designs. 👍 cc @hidde
