### ISSUE TITLE
After Search the search box is not collapsed 

### ISSUE THREAD

**Issue by hmitsch** [mozilla-iam/dino-park-issues#4]
On mobile this means that the staff|contributor filter is not visible.

**Comment by hidde** [comment]
I've just fixed this, change is in this PR https://github.com/mozilla-iam/dino-park-front-end/pull/137

**Comment by hidde** [comment]
This change was deployed, closing this issue.

**Comment by hidde** [comment]
Oh, I can't. Can you, @hmitsch?
