### ISSUE TITLE
create clearer click/tap targets for org chart view

### ISSUE THREAD

**Issue by janiceahn** [mozilla-iam/dino-park-issues#40]
Currently, the click (or tap) targets are not clear.

The common pattern is for carat to live on the far right. When user clicks on that row, expands or collapses.

In the beta, however, the carat for show more/less is on the far left.
When user clicks on row w/ a carat, the profile preview appears on right. So the expected expand/collapse doesn't happen.

Two possible solutions:
1) move carats to far right and add outline to differentiate targets
2) keep carat in same location but add outline to differentiate targets

**Comment by hmitsch** [comment]
@hidde can you please verify if this behavior is still the same in today's version of DinoPark. If yes, I'd suggest we file a medium priority Jira issue for the APR25 Milestone.

**Comment by hmitsch** [comment]
Tagging @mbransn to take a look.

**Comment by mbransn** [comment]
@janiceahn thanks for the input. :) @hmitsch @HerminaC a couple of thoughts on way forward:

1. I overall agree that we're missing a piece of functionality here: when one clicks on a closed row that has children, the row should expand AND the profile preview card should be displayed. Alternatively, if one clicks on an already expanded row that has children the row should collapse AND the profile preview card should be displayed. IMO this feature doesn't need an additional button, it should be triggered by click/tap of the row itself. See below (click to enlarge):

![start](https://user-images.githubusercontent.com/18686986/56620260-3271b000-65dd-11e9-8211-c84edbc64382.png)
![current](https://user-images.githubusercontent.com/18686986/56620275-3e5d7200-65dd-11e9-83d9-14ed4cffb6ff.png)
![expected](https://user-images.githubusercontent.com/18686986/56620287-43babc80-65dd-11e9-816f-7ccb90034b6d.png)

2. The approach of expand/collapse tree UI on the left was chosen to help with the shift from Phonebook to this new tool. I recommend leaving it for the continued beta period and gathering more insights/feedback.
3. Based on feedback, we may want to create and test alternate design options for expand, collapse and select targets before changing further.

**Comment by hmitsch** [comment]
Handing this over to @HerminaC.
@mbransn thanks for the detailed feedback.
