### ISSUE TITLE
BlueSky: Expanding DinoPark for Easier "What am I like? /  Who am I?"

### ISSUE THREAD

**Issue by gregglind** [mozilla-iam/dino-park-issues#41]
At Mozilla, we don't have a great place for 
- enabling Designed Alliance (working together rules)
- talking about Emotional Labor
- how interact as humans

As a design, I wonder how to collect and share info like:
- my outside life:  (cats, kids, cars, my D&D character)
- I want early stage feedback on things / leave me alone until the project is ready
- weird / rare hobbies

How would I get to know a new person I work with?  Where is the API for Henrik  :)

**Comment by hmitsch** [comment]
Great ideas, thanks a lot. Labeling as "question", because we would have to further explore this. At the moment, this is not on our roadmap.
