### ISSUE TITLE
BlueSky:  The Face Game

### ISSUE THREAD

**Issue by gregglind** [mozilla-iam/dino-park-issues#42]
User Story:  As a remote worker, who rarely interacts in person, I want to tie Faces to people and facts, so that I am not surprised / can get more out of all hands.  I have no idea of what most people look like :)

Design:
- a faces / facts / names game.  
- for a silo (all of Person X's undertree), a 'view all at once' version.

**Comment by hmitsch** [comment]
With the arrival of IAM/DinoPark _Edit Mode_ (April 2019) and the availability of the Person API V2, such an application can be built easily now. 
API Announcement: https://discourse.mozilla.org/t/iam-cis-person-api-v2-beta-test/37157

Building such a _Face Game_ is not currently in scope for the _IAM Project_, but we will be happy to support anybody who is going to work on it. By the way, Mozilla Reps built something similar a few years ago: **Rep Who?** at https://github.com/debloper/repwho
