### ISSUE TITLE
"what I did before here"

### ISSUE THREAD

**Issue by gregglind** [mozilla-iam/dino-park-issues#43]
- Searchable
- pull from LinkedIn?
- Supports:  "Who worked at Company X?"

**Comment by hmitsch** [comment]
Thanks for the suggestion. Certainly something worth exploring further down the road. For the moment the best workaround is to edit your `bio` field.

**Comment by hmitsch** [comment]
Also, you can search for data in the `bio` field with this syntax:
`description:"something"`

We actively decided against adding bio to the fields that are searched by default because that was one of the features people didn't like about phonebook.
