### ISSUE TITLE
Update beta/staging instance at least daily

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-iam/dino-park-issues#44]
Sometimes when I search dinopark, I notice that the entry for a new hire is missing or that a person who has left is still found. On phonebook, those are updated accordingly.
Can you increase the update interval for the data, please? Once a day or more often would be optimal. Thank you.

**Comment by hmitsch** [comment]
Hi @Archaeopteryx, during the _beta phase_ we rely on manual updates. Sorry for this! We plan to update later this week and will ping here once this is done.

One of our main goals for moving to "fully fledged scope" is to have real-time integration for Staff profile data.

Best regards,
   Henrik

**Comment by hmitsch** [comment]
We refreshed the data today. Closing this, because we track the proper buildout in separate issues.

-Henrik
