### ISSUE TITLE
make profile detail page columns aligned

### ISSUE THREAD

**Issue by janiceahn** [mozilla-iam/dino-park-issues#46]
The two columns of the top profile area and the more details area below (Colleagues, etc.) aren't aligned. Would be more pleasant/easier to parse through if aligned.

**Comment by hmitsch** [comment]
@mbransn is this something we want to iterate on before the APR 25 Milestone?

**Comment by mbransn** [comment]
Thanks @hmitsch, this is indeed something we've worked on and are improving with the next release. While still not perfectly aligned, we've gotten closer. @janiceahn pain points are card content padding vs. card sizes below. Happy to jump on a call and pick your brain about it sometime in the near future if you'd like (guerilla critic style!). :)
