### ISSUE TITLE
show more at top of profile detail page not worth amount of content hidden

### ISSUE THREAD

**Issue by janiceahn** [mozilla-iam/dino-park-issues#47]
The amount of content beneath the "show more" button at top of profile detail page is minimal and does not justify the button / click required to show it. Suggestion is to surface the content and de-emphasize it if not important, or consider moving to another section.

**Comment by hmitsch** [comment]
Thanks for this feedback, @janiceahn. With the arrival of _Edit Mode_ the box holds more information. That's the reason for our design decisions. I am pasting some screenshots. You will get an update in the next few days once we are launching this version to our beta audience (which includes you).

## _More Information_ **NOT** Expanded
![image](https://user-images.githubusercontent.com/869692/55784701-62836400-5ab1-11e9-8d23-eb6997787bb2.png)

## _More Information_ Expanded
![image](https://user-images.githubusercontent.com/869692/55784711-6911db80-5ab1-11e9-9261-81907f2dcc4e.png)

Closing issue. Feel free to reopen if you think this is not addressed properly.
