### ISSUE TITLE
carat and modal for contact me button on profile detail previews & page confusing

### ISSUE THREAD

**Issue by janiceahn** [mozilla-iam/dino-park-issues#48]
The carat within in the Contact Me button is confusing. Seems like extra work for user to click to reveal and then click again to hide. How many max types of contact might be listed? Could the contact information be exposed?

**Comment by hmitsch** [comment]
Closing issues as WONTFIX. Our next iteration of DinoPark will include **Edit Mode**. This allows you to select which contact modes to show in the _Contact Me_ button.

<img width="728" alt="image" src="https://user-images.githubusercontent.com/869692/55784201-59de5e00-5ab0-11e9-9c3c-ff16ae0e2cab.png">


<img width="343" alt="image" src="https://user-images.githubusercontent.com/869692/55784225-69f63d80-5ab0-11e9-814e-0d6b9f155eef.png">
