### ISSUE TITLE
photos from phonebook aren't appearing

### ISSUE THREAD

**Issue by lime124** [mozilla-iam/dino-park-issues#49]
it's not clear why the photos from phonebook aren't being pulled in. some people have photos while others (like myself) don't. my photo has been in phone book for a long time.

**Comment by hmitsch** [comment]
Closing as WONTFIX. With the new version of DinoPark which will be launched to our beta audience (this includes you @lime124) very, very soon we took a different route:

> In the next release, you can **Edit Your Profile**! By uploading a fresh profile picture you help us level set the photo data classification, ensuring your image is only shared with sites behind SSO when you set its visibility level to “public”. 

A longer background story on this can be found in this NDA classified Discourse article: https://discourse.mozilla.org/t/profile-picture-privacy-setting/37908
