### ISSUE TITLE
Search highlight in org chart is very faint

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla-iam/dino-park-issues#50]
I was looking at someone's profile on the people directory and then clicked "go to org chart" then it took me a few seconds to notice the highlight and find them again. 

I think making the colour a little bit brighter would help a lot!

**Comment by hmitsch** [comment]
@mbransn what's your thought about this?

For anybody who agrees to this issue, please upvote it (by pressing the thumbs up 👍 above).

**Comment by mbransn** [comment]
Thanks both, I'd like to gather some more feedback with the next release before we make a wide change. I respect what you're highlighting @LucyeoH (pun intended!) and will keep an eye on it as we evolve the style library.

Other potential solutions to mention: make the blue left border more prominent/thicker; move the blue left border to the right side. This is a great thing to test. :)
