### ISSUE TITLE
Feature request: Show number of directs for each manager

### ISSUE THREAD

**Issue by hmitsch** [mozilla-iam/dino-park-issues#51]
From a Discourse comment:
> I would be interested to see, for example, how many people are working on data within Mozilla. A little number beside each manager’s name, representing the total number of people below them, could help with that.

Source: https://discourse.mozilla.org/t/feature-request-show-number-of-directs-for-each-manager/37398

**Comment by openjck** [comment]
Quick clarification. *Directs* was the wrong word to use. I mean everyone below a person. Chris would have a higher number than Mark, Mark would have a higher number than Dave, etc.

**Comment by hmitsch** [comment]
@fiji-flo is this something we can technically do at all?

**Comment by hmitsch** [comment]
No technical blocker. So we need to explore the UX implications. @mbransn, do you remember the outcomes from previous conversations on this subject?

**Comment by mbransn** [comment]
Thanks for the loop in @hmitsch -- I don't know that we've discussed specifically outlining the number of reportees next to a managers name in the org chart. That is indeed one solution to the question outlined above, another is already live via search results:

<img width="323" alt="Screen Shot 2019-04-19 at 3 57 34 PM" src="https://user-images.githubusercontent.com/18686986/56447564-e0b7e580-62bd-11e9-9b25-21c990ed6b1a.png">

At this point in the beta I'd advocate for keeping this issue open and seeing what attention it attracts. Keeping the org chart informational at a glance and clutter free is a priority to aid in cognitive load when scanning. Of course if enough people think this would help we could test it out. :)
