### ISSUE TITLE
Username (and Page Title) default to an encoded string

### ISSUE THREAD

**Issue by tristanweir** [mozilla-iam/dino-park-issues#54]
When I edit my profile, I see the following string in Username:

> r--IapujEjrW_GDRayVlOmPXw==

This is replicated in the page title "r--IapujEjrW_GDRayVlOmPXw== - Profile - Mozilla Directory" (see issue #34)

The same is true for my manager and direct reports, but with different encoded strings

**Comment by hmitsch** [comment]
Hi @tristanweir, thanks for reporting this issue. You are the first person to hit our _Edit Mode_ alpha version and report an issue. Yay!!

The encoded string you mention is your initial `primary_username`. The `primary_username` has a PUBLIC data classification. For this reason, every new profile gets a random string assigned. You can change it, as you did, and you will see that your profile is now having `weir` as `primary_username`. This is also reflected in the profile URL and title tag: https://people.mozilla.org/p/weir

We still struggle with some data update times and are currently working on this. That's why a search for you currently ends up on your old profile (https://people.mozilla.org/p/r--IapujEjrW_GDRayVlOmPXw==) - which does not exist any longer. This is a different topic and I am therefore closing this issue.

Best regards,
   Henrik

**Comment by tristanweir** [comment]
I'd argue it is still strange UX. I might propose the following changes:

1. If a user has not set a username, the username field of the profile Editor should be blank (even if the `primary_username` field is set internally).
2. If a user has not set a username, the page title should just be "Profile - Mozilla Directory" or "Mozillian - Profile - Mozilla Directory".

Overall, while I understand the technical choices that led to this, I think the random string will raise more questions than answers if you display it anywhere other than the URL to the profile.

Otherwise, things look awesome!

**Comment by hmitsch** [comment]
Hi @tristanweir,

thanks for insisting and making your point much clearer. This is helpful. I am re-opening the issue and will consult @mbransn when she is back from PTO.

Best regards,
   Henrik

**Comment by hmitsch** [comment]
Cross-reference: https://jira.mozilla.com/browse/DP-1223 (sorry, this sits behind _Mozilla IAM_).

**Comment by hmitsch** [comment]
@tristanweir, by the way, there is a feature we had not mentioned:

Of course, you are right about the page title.

If a user still has their "default username" (e.g. `r--bWRu6ZNvVOu9vpqnLHBwxQ==`), we **hide** the username from the profile card. This way the UI stays clean.

Cool, eh?
Best regards,
   Henrik

**Comment by hidde** [comment]
I think what this issue really brings up is that our randomly generated usernames are too long and hard to read. We fixed it by hiding them from the profiles, and could do the same for page titles and even the username field (although that adds some complexity).

What if we generated usernames from random words (as Netlify's CI/CD does for URLs it deploys to)? The risk there would be that people could accidentally end up with insulting usernames, so we would have to be careful what to use.

**Comment by gdestuynder** [comment]
we definitely ran into the "this is offensive" issue when auto generating passwords a few years back. its not just insults, but some combinations of words can be offensive to some people depending on their background/culture/etc as they can mean different things even.

For usernames at least they only need to be unique, which is nice. I guess we could either:
- ask people when they first login to change it to whatever they want
- use someone elses generator that is deemed "safe" (ive seen plenty like the one @hidde mentions that aren't good for passwords but great for project names, usernames, etc)

**Comment by mbransn** [comment]
As for username generation, is it possible to generate based on their email or another attribute (similar to the Identicon?). If not, ideally the UX would enable a clean field and page title until one is self-attributed by the profile owner.

>- ask people when they first login to change it to whatever they want

This makes sense as part of an onboarding flow and is a story I'd love to capture for that future work cc @HerminaC

**Comment by gdestuynder** [comment]
The problem when basing it on email is that it discloses personal information as the dinopark username is public / used to generate your profile URL - you can always change it to that afterwards though
