### ISSUE TITLE
Bio values no longer render the markup

### ISSUE THREAD

**Issue by gene1wood** [mozilla-iam/dino-park-issues#55]
Previously text like

```
This is [https://example.com/foo my link text].
```

would render like

This is [my link text](https://example.com/foo).

but now it just renders as

This is [https://example.com/foo my link text].

**Comment by gene1wood** [comment]
Oh, it looks like we're rendering `markdown` (I just happened upon this). We should probably indicate that in the UI somewhere

**Comment by hmitsch** [comment]
Yes, we will add `info buttons`, to all fields. This is what the design looks like:

<img width="632" alt="image" src="https://user-images.githubusercontent.com/869692/55943570-1c600900-5c47-11e9-95ee-390a26b8907e.png">

Closing issue, as it is in scope for the APR 25 Milestone.

**Comment by hmitsch** [comment]
This is the Jira issue which tracks this capability: https://jira.mozilla.com/browse/DP-1017 (As a user I want be able to click on an info icon to view more information)
