### ISSUE TITLE
Subjective : Visual positioning of pronouns is confusing

### ISSUE THREAD

**Issue by gene1wood** [mozilla-iam/dino-park-issues#59]
![Selection_036](https://user-images.githubusercontent.com/1134034/55961401-a9916680-5c23-11e9-8fb3-9532bd03698a.png)

The 4 or 5 spaces between the username and pronouns is, to me, visually confusing. Each time I see it, it looks like a sentence initially and then I realize what's going on.

Is there any way to add more differentiation between the username and the pronouns (which I'm assuming have little to do with each other and aren't positioned so close to each other for a reason due to their relatedness)?

For example
* increase the distance between them
* right justify the pronouns to the right side of the name
* add a visual differentiator like a vertical line

**Comment by hmitsch** [comment]
Requesting @hidde to take a look. Do you know if we have a reason for the current positioning?

**Comment by hidde** [comment]
In our most recent designs, we have a separator between username and pronouns, like this: 

<img width="244" alt="shows username, a vertical separator and pronouns" src="https://user-images.githubusercontent.com/178782/56114907-7a039680-5f62-11e9-8daf-37bc30e8016a.png">

Filed as[DP-1240](https://jira.mozilla.com/browse/DP-1240),  ready for prioritisation.

**Comment by viorelaioia** [comment]
This issue is fixed in prod.
