### ISSUE TITLE
Design vs. Real Data: Time Zones missing?

### ISSUE THREAD

**Issue by hmitsch** [mozilla-iam/dino-park-issues#6]
**Design:**
<img width="371" alt="image" src="https://user-images.githubusercontent.com/869692/48774488-b8a26700-ecca-11e8-832e-3705cc174df3.png">

**Real Data:**
<img width="383" alt="image" src="https://user-images.githubusercontent.com/869692/48774486-b6400d00-ecca-11e8-9861-fe715c700f93.png">

Do we not get the `time zone` from Profile V2?

**Comment by hidde** [comment]
I'm not sure if we do or not… @fiji-flo do you?

**Comment by mbransn** [comment]
I thought we did. Would be really great to see for this release if available. 🙏

**Comment by hidde** [comment]
They were indeed missing, but have been added in prod this weekend by @fiji-flo. 🎉
