### ISSUE TITLE
Clicking on whitespace left of a dropdown arrow in org chart hides dropdown arrow

### ISSUE THREAD

**Issue by tristanweir** [mozilla-iam/dino-park-issues#62]
When using the org chart view, clicking on the whitespace to the left of a manager's dropdown arrow hides the dropdown arrow. Clicking anywhere outside that manager's name restores it. This is a minor inconvenience if you happen to misclick when trying to expand a manager's direct reports.

This visual bug also occurs on non-managers (the dot disappears) but the dot provides no interaction so no functionality is lost by the dot going missing.

Firefox 67.0b9

**Comment by viorelaioia** [comment]
Hi @tristanweir ! We are tracking the progress of this issue in [DP-1212](https://jira.mozilla.com/browse/DP-1212), will add a comment here when it's fixed.

**Comment by rleitan** [comment]
This issue is fixed!
