### ISSUE TITLE
Public field data not really public

### ISSUE THREAD

**Issue by gene1wood** [mozilla-iam/dino-park-issues#65]
This may be an artifact of Dinopark being in beta and this naturally gets fixed when we enter general availability (which if that's the case close/ignore this issue).

If I set a field in my profile as public and then browse to my profile URL from another browser that I'm not logged into Auth0 on (e.g. https://people.mozilla.org/p/gene ) I'm redirected to an Auth0 login and have to login to continue.

This means a few things
* Unlike the current mozillians.org website, user profiles won't be reachable anonymously
* Search engines won't be able to access and index public data in profiles

I feel like "Public" has two aspects to it's meaning. 

1. It means a data classification indicating what group of people have access to the data
   * This use works here since indeed anyone can login with a passwordless email loop login and see the data
2. It also means something that's available unauthenticated and anonymously on the internet
   * This usage doesn't really work in this case

I think we should surface public dinopark data in user profiles, read only in an unauthenticated way to conform to existing mozillians.org behavior, user expectations, and being a healthy internet citizen enabling search engines and other systems to access this public data.

**Comment by hmitsch** [comment]
Hi @gene1wood,

> This may be an artifact of Dinopark being in beta and this naturally gets fixed when we enter general availability (which if that's the case close/ignore this issue).

**Spot on!** Indeed, we will add public landing pages, as we exit the beta phase and enter into a phase where DinoPark will become _publicly accessible_.

-Henrik
