### ISSUE TITLE
Unable to add profile picture

### ISSUE THREAD

**Issue by jgmize** [mozilla-iam/dino-park-issues#68]
When attempting to add a profile picture, I get the a message "a problem has occurred, please try again later". I copied the relevant request and response from the network panel in dev tools below, after verifying that there isn't any data I mind having in a public issue. 

- POST
  > {"operationName":"UpdateProfile","variables":{"picture":{"value":"https://s3.amazonaws.com/ldap2s3-replication-staging/pictures/ad|Mozilla-LDAP|jmize.jpg","display":"STAFF"},"primaryUsername":{"value":"jgmize","display":"PUBLIC"},"firstName":{"value":"Josh","display":"STAFF"},"lastName":{"value":"Mize","display":"STAFF"},"alternativeName":{"value":null,"display":"STAFF"},"funTitle":{"value":"Staff Site Reliability Engineer","display":"STAFF"},"pronouns":{"value":null,"display":"STAFF"},"location":{"value":null,"display":"STAFF"},"timezone":{"value":null,"display":"STAFF"},"description":{"value":"[https://www.mozilla.org]\r\n[https://developer.mozilla.org]\r\n[https://snippets.mozilla.com]\r\n[https://careers.mozilla.org]\r\n[https://viewsourceconf.org]\r\n[https://support.mozilla.org]\r\n[https://kubernetes.io]","display":"STAFF"}},"query":"mutation UpdateProfile($primaryUsername: StringWithDisplay, $alternativeName: StringWithDisplay, $description: StringWithDisplay, $firstName: StringWithDisplay, $funTitle: StringWithDisplay, $lastName: StringWithDisplay, $location: StringWithDisplay, $phoneNumbers: KeyValuesWithDisplay, $picture: StringWithDisplay, $pronouns: StringWithDisplay, $timezone: StringWithDisplay, $languages: KeyValuesWithDisplay, $uris: KeyValuesWithDisplay) {\n  profile(update: {primaryUsername: $primaryUsername, alternativeName: $alternativeName, description: $description, firstName: $firstName, funTitle: $funTitle, lastName: $lastName, location: $location, phoneNumbers: $phoneNumbers, picture: $picture, pronouns: $pronouns, timezone: $timezone, languages: $languages, uris: $uris}) {\n    uuid {\n      value\n      metadata {\n        display\n        __typename\n      }\n      __typename\n    }\n    primaryUsername {\n      value\n      metadata {\n        display\n        __typename\n      }\n      __typename\n    }\n    alternativeName {\n      value\n      metadata {\n        display\n        __typename\n      }\n      __typename\n    }\n    description {\n      value\n      metadata {\n        display\n        __typename\n      }\n      __typename\n    }\n    firstName {\n      value\n      metadata {\n        display\n        __typename\n      }\n      __typename\n    }\n    funTitle {\n      value\n      metadata {\n        display\n        __typename\n      }\n      __typename\n    }\n    lastName {\n      value\n      metadata {\n        display\n        __typename\n      }\n      __typename\n    }\n    location {\n      value\n      metadata {\n        display\n        __typename\n      }\n      __typename\n    }\n    phoneNumbers {\n      values\n      metadata {\n        display\n        __typename\n      }\n      __typename\n    }\n    picture {\n      value\n      metadata {\n        display\n        __typename\n      }\n      __typename\n    }\n    pronouns {\n      value\n      metadata {\n        display\n        __typename\n      }\n      __typename\n    }\n    timezone {\n      value\n      metadata {\n        display\n        __typename\n      }\n      __typename\n    }\n    uris {\n      values\n      metadata {\n        display\n        __typename\n      }\n      __typename\n    }\n    languages {\n      values\n      metadata {\n        display\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n}\n"}

- Response
  > {"data":null,"errors":[{"message":"expected value at line 1 column 1","locations":[{"line":2,"column":3}],"path":["profile"]}]}

**Comment by Phrozyn** [comment]
I want to add to this. I was able to upload a profile picture the first time, but then deleted it and went to add a new one and all subsequent attempts result in no functionality. The window that opened before to allow me to pick a photo is no longer opening.

Loading failed for the <script> with source “https://www.googletagmanager.com/gtm.js?id=GTM-5GCB5DL”. e:1:1
Content Security Policy: The page’s settings blocked the loading of a resource at https://www.googletagmanager.com/gtm.js?id=GTM-5GCB5DL (“script-src”).
Successfully compiled asm.js code (total compilation time 51ms) demangle.js
[Exception... "Component returned failure code: 0x805e0006 [nsIChannel.asyncOpen2]"  nsresult: "0x805e0006 (<unknown>)"  location: "JS frame :: resource:///modules/FaviconLoader.jsm :: load :: line 147"  data: no]
Content Security Policy: The page’s settings blocked the loading of a resource at https://avatars0.githubusercontent.com/favicon.ico (“default-src”).
Attempt to set a forbidden header was denied: Connection 2001224766-lcs_client_bin.js:137:386
OpenGL compositor Initialized Succesfully.
Version: 2.1 ATI-2.8.38
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon Pro 560 OpenGL Engine
FBO Texture Target: TEXTURE_2D

**Comment by fiji-flo** [comment]
@jgmize  debugging. I'll keep going for bit but I really need a weekend. Top on my list for Monday.
@Phrozyn could you specify this a little bit more? I hope this goes away after a reload (not that this must not happen at all, but it would calm my mind). Could tell me what browser / version?
> https://avatars0.githubusercontent.com/favicon.ico
scares me a little bit. What log is that?

**Comment by hmitsch** [comment]
Input for @fiji-flo: The Google Tag Manager ID `GTM-5GCB5DL` is the one we used on people.allizom.community. As far as I know, there is no Google tracking on people.mozilla.org, right?

**Comment by fiji-flo** [comment]
We block GA via CSP. Removing it now.

@jgmize I found your issue. Your imported data from LDAP corrupted your profile. That's a bug in https://github.com/mozilla-iam/cis we're aware of this but we had workarounds for all other form of broken profiles in place. Sorry for that. We're on it.

**Comment by Phrozyn** [comment]
> @jgmize debugging. I'll keep going for bit but I really need a weekend. Top on my list for Monday.
> @Phrozyn could you specify this a little bit more? I hope this goes away after a reload (not that this must not happen at all, but it would calm my mind). Could tell me what browser / version?
> 
> > https://avatars0.githubusercontent.com/favicon.ico
> > scares me a little bit. What log is that?

That is the browser console log using web developer tools when I attempted to add a new image. A reload did not work. I'm using Firefox 66.0.3 64bit

**Comment by gdestuynder** [comment]
This should now work

**Comment by jgmize** [comment]
Thanks!
