### ISSUE TITLE
404 /~ requests

### ISSUE THREAD

**Issue by cshields** [mozilla-iam/dino-park-issues#73]
the new phonebook is setup to take the place of an old shell/webserver we used to run, people.mozilla.org[com].  That webserver had years of content which became dead links when we decommissioned the service, but that doesn't mean those links went away.

Now - when someone follows one of those links they try an SSO auth and are met with an error that says "Sorry, you do not have permission to access ..  Please contact eus@mozilla.com if you should have access."

We've already seen one request come in to eus@mozilla.com asking for access to a link on the previous "people" instance.

IIRC, 99% of the data on people.mozilla.org/com were under personal docroots (/~foo). Unless dinopark needs personal docroots (I don't think it does), they should be given a 404 response *before* the auth0 attempt.

![image](https://user-images.githubusercontent.com/225283/56834673-0dc94280-6840-11e9-82ab-9f1b6c73143d.png)

**Comment by hmitsch** [comment]
Mirrored in https://jira.mozilla.com/browse/DP-1292 (sorry for the auth wall).

**Comment by fiji-flo** [comment]
Thanks for this we'll return a 404 for the `/~` prefix. Maybe we can revive docroots at some point :see_no_evil:

**Comment by fiji-flo** [comment]
https://people.mozilla.org/~fiji → 404

Please ping us if you see more emails. We still show the error page for / without authentication. We're talking about potentially having a landing page for that.
