### ISSUE TITLE
'alternative name' is not included in search fields

### ISSUE THREAD

**Issue by globau** [mozilla-iam/dino-park-issues#78]
steps to reproduce:
* add an alternative name to your profile, ensuring this name doesn't appear elsewhere in your profile
* search for this name

expected:
* your profile should be returned when searching for it

actual:
* profile not returned

**Comment by globau** [comment]
as an example, at mozilla i go by `glob`, so i've set that as my first name in my profile.  while i'll answer to my legal name, `glob` is my preferred name.

however as i want people to be able to find me by my real name - byron - i have that as my "alternative name".

the problem is https://people.mozilla.org/s?query=byron&who=staff doesn't return my profile.

**Comment by hmitsch** [comment]
Hi @globau,

thanks for checking in. The **alternate name** is currently not in the _default search_. You can access it, via ElasticSearch query syntax:

`alternativeName:byron`

This returns your profile.

At some point in the future, we will build "filters" (aka "search controls"), to make these search queries more accessible. Depending on the feedback we get, we might also add _alternate name_ to default search (https://github.com/mozilla-iam/dino-park-search/blob/master/lib/mapping.js#L102).

Best regards,
   Henrik

**Comment by globau** [comment]
thanks for the response.

i'm not in a position to tell people who don't know how to contact me how to perform a custom search on phonebook if they only know my legal, and not preferred name.

> Depending on the feedback we get, we might also add alternate name to default search

please consider this a strong vote for this change.

**Comment by smacleod** [comment]
> Depending on the feedback we get, we might also add _alternate name_ to default search

I was also extremely surprised by this, I also would strongly encourage making this the default.

**Comment by hmitsch** [comment]
@fiji-flo, how hard would it be to add _alternate name_ to the default search scope?

/cc @HerminaC

**Comment by globau** [comment]
As this is a high impact to me I've created a pull-request which should fix this issue - https://github.com/mozilla-iam/dino-park-search/pull/53

(cc @HerminaC)

**Comment by HerminaC** [comment]
Thanks a lot, @globau . @fiji-flo is currently on PTO, but we'll look at it together next Monday

**Comment by globau** [comment]
looks like this has been fixed as part of https://github.com/mozilla-iam/dino-park-search/pull/54

thanks!
