### ISSUE TITLE
Clicking back from non highlighted org user takes you to the root of the org view

### ISSUE THREAD

**Issue by gene1wood** [mozilla-iam/dino-park-issues#79]
1. Browse to https://people.mozilla.org/
2. Search for "henrik"
3. Click the org icon to the right of Henrik Mitsch and you're taken to https://people.mozilla.org/o/highlight/hmitsch
4. Click "View full profile" and you're taken to https://people.mozilla.org/p/hmitsch
5. Click back and you're taken back to the org view with Henrik highlighted and visible in the viewport
6. Click Viorela Ioia and you're taken to https://people.mozilla.org/o/viorelaioia
7. Click "View full profile" and you're taken to https://people.mozilla.org/p/viorelaioia
8. Click back

# Expected results

You're taken back to the org view with Viorela focused just as you were with Henrik

# Actual results

You're taken back to the org view to the root of the org with Mitchell Baker at the top

This could be fixed by changing the org view so that whenever you select a user, the URL changes to https://people.mozilla.org/o/highlight/viorelaioia for example

**Comment by hmitsch** [comment]
Nice edge case! Paging @fiji-flo to hear his opinion on this issue. :-)
