### ISSUE TITLE
null null in manages tooltip

### ISSUE THREAD

**Issue by hmitsch** [mozilla-iam/dino-park-issues#8]
Hovering over a name in the `Relations` component shows `null null`:
<img width="311" alt="image" src="https://user-images.githubusercontent.com/869692/48808262-92a7b180-ed20-11e8-8fb5-783325b3778c.png">

Can we improve that?

**Comment by fiji-flo** [comment]
Lovely case of snake vs camel case. Will be fixed. This also brings back the _name_ field in the _reports to_ section.

**Comment by hidde** [comment]
Note this is also reported in DP-704, I'll assign that to you too, Florian.

**Comment by fiji-flo** [comment]
resolved
