### ISSUE TITLE
IRC account not identified as "Mozilla"

### ISSUE THREAD

**Issue by globau** [mozilla-iam/dino-park-issues#81]
After adding an IRC account it appears in an `Elsewhere` box.  This confusing and possibly incorrect.

There are multiple IRC networks, and as it happens I use a different name on irc.mozilla.org than others (such as freenode).  I'm expecting the IRC account on my people account should refer to my nick on irc.mozilla.org, however after adding it I see that's it's listed not as part of Mozilla, rather "Elsewhere".

The IRC account shouldn't be "Elsewhere", or it should be prefixed with the relevant IRC network name so people know which nick to use (eg "Freenode IRC").

**Comment by hmitsch** [comment]
@mbransn what's your thinking about this?

**Comment by mbransn** [comment]
@globau I do agree with you on this (apologies for delayed reply!). At the least this first implementation should support that IRC is 'Mozilla IRC'. In the future we'd like to enable people to enter other accounts, including unique prefixes for IRC, Slack, etc. The timeline for this isn't quite clear to me yet, @fiji-flo do you have any insight? And @hidde is it possible to prefix IRC with Mozilla so it's categorized more clearly? cc @HerminaC @viorelaioia

**Comment by hidde** [comment]
Do we potentially have a use case for people who want to add their IRC that is _not_ Mozilla IRC, ie contributors? If we change 'IRC' to 'Mozilla IRC' without having 'Freenode IRC', we would no cease to facilitate those people's needs?

**Comment by globau** [comment]
> Do we potentially have a use case for people who want to add their IRC that is not Mozilla IRC, ie contributors?

Yes - especially after the Mozilla IRC network is shutdown.

> If we change 'IRC' to 'Mozilla IRC' without having 'Freenode IRC', we would no cease to facilitate those people's needs?

Keep in mind there's more than just two IRC networks, and it's possible to have different usernames on each of them.  It might be a slippery slope to start supporting all of them.

As my primary concern with this issue is the current IRC network, which is most likely to be expected to be a reference to _our_ IRC network, is not external/elsewhere and should not be labelled as such.

My suggestion here would be to just move the current IRC field from Elsewhere to Mozilla.

Then, once the Mozilla IRC network has been discontinued, look at which networks our official communities have moved to (IRC or otherwise) and provide fields for those.

**Comment by hidde** [comment]
Thanks, @globau. 

Just to keep you posted, we are addressing this in a nearby release, I've just PR'ed a fix. Thanks again for your feedback!
