### ISSUE TITLE
When viewing someone else's profile without accounts, the "no accounts" message refers to "you"

### ISSUE THREAD

**Issue by globau** [mozilla-iam/dino-park-issues#82]
When viewing someone else's profile without accounts the following is displayed:
> You haven’t added any accounts yet.

The "You" in this context doesn't make sense; I can't add accounts to anyone else's profile.

Perhaps that section shouldn't be visible when viewing someone else's profile if it's empty?

**Comment by hidde** [comment]
Hello @globau , thanks for filing this! We're [updating this copy](https://github.com/mozilla-iam/dino-park-front-end/pull/332) to become:

> No accounts have been added yet.

This should make more sense. 

Thanks also for your suggestion. The reason we currently display display the empty ‘No Accounts’ section, as opposed to no section at all, is continuity between profiles. 

cc @mbransn for visibility
