### ISSUE TITLE
Javascript error when searching with empty query: `TypeError: "this.searchQuery is undefined"`

### ISSUE THREAD

**Issue by globau** [mozilla-iam/dino-park-issues#83]
performing a search when `#search-query` is empty results in following javascript error:

```
TypeError: "this.searchQuery is undefined"
    handleSubmit SearchForm.vue:76
```

**Comment by hmitsch** [comment]
Nice catch, thank you!
/cc @fiji-flo

**Comment by hmitsch** [comment]
Also cc @viorelaioia @rleitan 😄

**Comment by fiji-flo** [comment]
resolved in https://github.com/mozilla-iam/dino-park-front-end/pull/313

Thanks for reporting.

**Comment by fiji-flo** [comment]
Will be deployed within the hour.
