### ISSUE TITLE
Last Modified Date

### ISSUE THREAD

**Issue by luciusbono** [mozilla-iam/dino-park-issues#85]
It would be extremely useful to have a last modified date for users profiles, or even better a last modified date for certain pieces of information. 

Reason: there are instances where users may need to quickly verify each other's identity quickly via an out-of-band system. I could call or text the number listed in a user's profile, but what if that number was maliciously changed? A date stamp doesn't completely thwart this type of attack, but seeing that a number was recently changed could signal that number is not a valid out-of-band identification path. 

Photo would be useful as well, since a video call could be a valid identification path. Ideally these would have separate dates so the older data could be chosen.

**Comment by hmitsch** [comment]
Hi @luciusbono,

thanks for checking in. I will defer to @gdestuynder, hoping that he has a good answer for you.

I do know that the API request we make has two fields you might be interested in:
* `last_modified`
* `created`

However, we chose **not** to make this data visible in the people directory as we do (did) not think it would be of much help. Depending on where this thread is going, we might want to loop in our UX authority (@mbransn).

-Henrik

**Comment by gdestuynder** [comment]
@luciusbono The CIS API contains the last modified information as per Henrik's msg. This data is available to Infosec but not viewers of DinoPark. If DinoPark would like to show this data, they could, though they might want to expose it a different way such as "/!\ This phone number was last modified more than a year ago" or to prompt users to update their data from time to time for example.

**Comment by luciusbono** [comment]
It's useful to know that Infosec had access to modification dates, and
maybe I'm running too far with this idea, but it does seem like Dinopark
could be a really helpful tool for helping users do quick out of band IDV.

I was walking through a phishing mitigation training the other day and one
of the main defenses that it suggested users had against spearphishing
attacks ("the CEO needs you to wire transfer money right now", etc) is out
of band verification. They suggest calling the employee, for example.

Maybe Dinopark was never intended to be an identity verification tool, so
maybe this request is just headed in the wrong direction, but it would
certainly make my life easier as an employee if I could tell people: "call
my cell phone or request a video call with me in any situation where
verifying my identity is critical" and they could verify that the
information in Dinopark is old enough to likely not have been recently
tampered with.
