### ISSUE TITLE
Firefox Night Mode makes the Search icon into an easter egg (e.g. invisible!)

### ISSUE THREAD

**Issue by kwillowhawk** [mozilla-iam/dino-park-issues#88]
I was needing to lookup a Mozillian while in a Zoom on my iPad, so I trucked out the mobile phone running our internal Firefox on iOS build 17.3, sporting "Night Mode" enabled (think Dark Mode but more CSS fiddly).  To my dismay I could not find a way to search for a person.  There was no search field or button or function anywhere.  Turns out that it's there and happily clickable but with Night Mode enabled, it renders black-on-black as to be invisible.
![UNADJUSTEDNONRAW_thumb_281a](https://user-images.githubusercontent.com/50632540/58836800-ff2c3300-8616-11e9-955b-c41345d5f027.jpg)
![UNADJUSTEDNONRAW_thumb_2820](https://user-images.githubusercontent.com/50632540/58836801-ff2c3300-8616-11e9-9412-4318c0e81d68.jpg)

**Comment by HerminaC** [comment]
Hey,

Thanks a lot for sending this! We're looking into it. Will comment here with updates.
