### ISSUE TITLE
GitHub identity not shown in edit UI after linking

### ISSUE THREAD

**Issue by gene1wood** [mozilla-iam/dino-park-issues#89]
# Steps to reproduce

* In your dinopark account, link your GitHub account
* Visit your profile page

# Expected results

Like my linked Bugzilla account, which shows my Bugzilla identity (my bugzilla email), I would expect my linked GitHub account to show my GitHub identity (my GitHub username)

# Actual results

The GitHub identity box is empty

![Selection_067](https://user-images.githubusercontent.com/1134034/59296871-d2da6d00-8c3b-11e9-86ac-7f890f708e36.png)

![Selection_066](https://user-images.githubusercontent.com/1134034/59296878-d5d55d80-8c3b-11e9-9c0a-7feca1487dda.png)

**Comment by gene1wood** [comment]
After about 10 minutes I noticed it started showing up

![Selection_068](https://user-images.githubusercontent.com/1134034/59297597-6f513f00-8c3d-11e9-9c5a-085fa2dac921.png)

How weird. I this some kind of CIS latency thing? Are other types of changes to one's profile delayed by this much sometimes?

Or did someone see this bug report and manually do something on the backend in the last 10 minutes?

**Comment by floatingatoll** [comment]
I noticed this as well; it's been at least 10 minutes since I linked it, and it shows GitHub Verified but no username.
