### ISSUE TITLE
UI says to add/remove email via identities. Identities doesn't add/remove email

### ISSUE THREAD

**Issue by gene1wood** [mozilla-iam/dino-park-issues#90]
In the email edit UI the UI says "Add / Remove Email via Identities"

![Selection_065](https://user-images.githubusercontent.com/1134034/59296963-02897500-8c3c-11e9-8528-18fc0dbcfcbb.png)

The identities pane however has nothing related to emails

![Selection_067](https://user-images.githubusercontent.com/1134034/59296992-11702780-8c3c-11e9-974a-1faf729524f4.png)

**Comment by april** [comment]
I would also love to change my email address from the official LDAP version.  :)

**Comment by fiji-flo** [comment]
We changed to copy here. We'll work on adding emails (#127 and others).
