### ISSUE TITLE
My profile doesn't show any Colleagues

### ISSUE THREAD

**Issue by mkaply** [mozilla-iam/dino-park-issues#93]
When I go to my profile, I have no colleagues :)

**Comment by flodolo** [comment]
I wonder if the design, or the naming, is misleading here. 

If I look at my manager, I see he has two rows: "Reports to" and "Manages". I only have a "Reports to" line. 

The confusion is that "Colleagues" should also include my teammates, but they don't show up here (would they need a "Other team members" row?).
