### ISSUE TITLE
Small Avatar profile picture looks grainy

### ISSUE THREAD

**Issue by flekkowich** [mozilla-iam/dino-park-issues#97]
Firefox Nightly 69.0a1 (2019-06-27) (64-bit)
Mac OS 10.14.4 (18E226)

Avatar in top right corner looks very grainy, but profile pic in full profile view looks fine.

**Comment by floatingatoll** [comment]
My profile pic in the top right corner looks blurry, as if it was resized twice. It's at /avatar/get/id/...?size=40 and the HTML source indicates that we're not offering a high-DPI alternative image. Maybe it was probably resized once (down from my large pic) and then up by 2x (lo-DPI image on hi-DPI display)?

```<img alt="" role="presentation" aria-hidden="true" src="/avatar/get/id/hashhashhashhashhashhashetc.png?size=40" width="40">```

Nightly, MacOS 10.14, iMac 21.5" Retina
